### ISSUE TITLE
Does mindspore support frozen model deploy on GPU?

### ISSUE THREAD

**Issue by zjd1988** [mindspore-ai/mindspore#10]
I have checked the documents,and not found anything about deploy on GPU with a frozen model.

**Comment by kingxiaoxian** [comment]
By frozen model if you are referring to freezing and then [restoring of the model](https://medium.com/@prasadpal107/saving-freezing-optimizing-for-inference-restoring-of-tensorflow-models-b4146deb21b5), currently MindSpore supports frozen model via exporting to ONNX model for inference usage on backends like GPU. In addition, MindSpore supports load checkpoint with network resouce code on gpu, which is saved from training. You can get example from our [tutorial](https://www.mindspore.cn/tutorial/en/master/use/saving_and_loading_model_parameters.html).

**Comment by zjd1988** [comment]
@kingxiaoxian  thanks for your reply.  :)
