### ISSUE TITLE
Failed to compile mindspore

### ISSUE THREAD

**Issue by zzqq2199** [mindspore-ai/mindspore#101]
Hello, developers!
Following [instructions](https://www.mindspore.cn/install), I tried to compile mindspore on my machine, but encounter a compiling error.

> configure: WARNING: See config.log for details
> configure: error: Cannot continue
> CMake Error at cmake/utils.cmake:174 (message):
>   error! when ./configure;CXXFLAGS=-D_FORTIFY_SOURCE=2
>   -O2;--prefix=/home/mindspore/source/mindspore/build/mindspore/.mslib/ompi_43222b5b12a55cfa6bc138b1ee01470b
>   in /home/mindspore/source/mindspore/build/mindspore/_deps/ompi-src
> Call Stack (most recent call first):
>   cmake/utils.cmake:380 (__exec_cmd)
>   cmake/external_libs/ompi.cmake:3 (mindspore_add_pkg)
>   cmake/mind_expression.cmake:44 (include)
>   CMakeLists.txt:37 (include)

Detailed messages in CMakeOutput.log is pasted below: 

> Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
> Change Dir: /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_e2f2a/fast && /usr/bin/make  -f CMakeFiles/cmTC_e2f2a.dir/build.make CMakeFiles/cmTC_e2f2a.dir/build
> make[1]: Entering directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_e2f2a.dir/src.c.o
> /usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_e2f2a.dir/src.c.o -c /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/src.c
> Linking C executable cmTC_e2f2a
> /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e2f2a.dir/link.txt --verbose=1
> /usr/bin/cc CMakeFiles/cmTC_e2f2a.dir/src.c.o -o cmTC_e2f2a
> CMakeFiles/cmTC_e2f2a.dir/src.c.o: In function `main':
> src.c:(.text+0x3e): undefined reference to `pthread_create'
> src.c:(.text+0x4a): undefined reference to `pthread_detach'
> src.c:(.text+0x56): undefined reference to `pthread_cancel'
> src.c:(.text+0x67): undefined reference to `pthread_join'
> src.c:(.text+0x7b): undefined reference to `pthread_atfork'
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_e2f2a.dir/build.make:105: recipe for target 'cmTC_e2f2a' failed
> make[1]: *** [cmTC_e2f2a] Error 1
> make[1]: Leaving directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_e2f2a/fast' failed
> make: *** [cmTC_e2f2a/fast] Error 2
> 
> 
> Source file was:
> #include <pthread.h>
> 
> static void* test_func(void* data)
> {
>   return data;
> }
> 
> int main(void)
> {
>   pthread_t thread;
>   pthread_create(&thread, NULL, test_func, NULL);
>   pthread_detach(thread);
>   pthread_cancel(thread);
>   pthread_join(thread, NULL);
>   pthread_atfork(NULL, NULL, NULL);
>   pthread_exit(NULL);
> 
>   return 0;
> }
> 
> Determining if the function pthread_create exists in the pthreads failed with the following output:
> Change Dir: /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_cbe5d/fast && /usr/bin/make  -f CMakeFiles/cmTC_cbe5d.dir/build.make CMakeFiles/cmTC_cbe5d.dir/build
> make[1]: Entering directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_cbe5d.dir/CheckFunctionExists.c.o
> /usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_cbe5d.dir/CheckFunctionExists.c.o -c /usr/local/share/cmake-3.19/Modules/CheckFunctionExists.c
> Linking C executable cmTC_cbe5d
> /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_cbe5d.dir/link.txt --verbose=1
> /usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_cbe5d.dir/CheckFunctionExists.c.o -o cmTC_cbe5d  -lpthreads
> /usr/bin/ld: cannot find -lpthreads
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_cbe5d.dir/build.make:105: recipe for target 'cmTC_cbe5d' failed
> make[1]: *** [cmTC_cbe5d] Error 1
> make[1]: Leaving directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_cbe5d/fast' failed
> make: *** [cmTC_cbe5d/fast] Error 2
> 
> Determining if the __aarch64__ exist failed with the following output:
> Change Dir: /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp
> 
> Run Build Command(s):/usr/bin/make cmTC_2a041/fast && /usr/bin/make  -f CMakeFiles/cmTC_2a041.dir/build.make CMakeFiles/cmTC_2a041.dir/build
> make[1]: Entering directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_2a041.dir/CheckSymbolExists.c.o
> /usr/bin/cc    -o CMakeFiles/cmTC_2a041.dir/CheckSymbolExists.c.o -c /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/CheckSymbolExists.c
> /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
> /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/CheckSymbolExists.c:7:19: error: ‘__aarch64__’ undeclared (first use in this function); did you mean ‘__amd64__’?
>    return ((int*)(&__aarch64__))[argc];
>                    ^~~~~~~~~~~
>                    __amd64__
> /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/CheckSymbolExists.c:7:19: note: each undeclared identifier is reported only once for each function it appears in
> CMakeFiles/cmTC_2a041.dir/build.make:84: recipe for target 'CMakeFiles/cmTC_2a041.dir/CheckSymbolExists.c.o' failed
> make[1]: *** [CMakeFiles/cmTC_2a041.dir/CheckSymbolExists.c.o] Error 1
> make[1]: Leaving directory '/home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp'
> Makefile:140: recipe for target 'cmTC_2a041/fast' failed
> make: *** [cmTC_2a041/fast] Error 2
> 
> 
> File /home/mindspore/source/mindspore/build/mindspore/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
> /* */
> 
> int main(int argc, char** argv)
> {
>   (void)argv;
> #ifndef __aarch64__
>   return ((int*)(&__aarch64__))[argc];
> #else
>   (void)argc;
>   return 0;
> #64

 

I sincerely hope you can give me some instructions how to fix this bug. Thank you in advance!

**Comment by zpcalan** [comment]
Hi, the reason could be that the version of ompi installed on your host is not the same as ompi that MindSpore uses.
Please check the ompi version which is installed:
`mpirun --version`.
And tell us the version or commit id of MindSpore source you try to compile.

**Comment by zzqq2199** [comment]
Thank you! I find that another ompi3.3 was installed through `apt install`, thus overwrote the previously installed ompi3.1.5. 

> success building mindspore project!
