### ISSUE TITLE
我进行mindir转换为ms格式文件时，报错了，但是转换成功了，也得到了.ms文件，请问这样是否转换成功？报错如下：

### ISSUE THREAD

**Issue by gyr-kdgc** [mindspore-ai/mindspore#103]
root@7230313abe8a:~/mindspore/output/mindspore-lite-1.1.0-converter-linux-x64/converter# ./converter_lite --fmk=MINDIR --modelFile=../../../../mindspore_mnist/checkpoint_lenet-1_1875.mindir --outputFile=checkpoint_lenet-1_1875  
 
WARNING: Logging before InitGoogleLogging() is written to STDERR
[ERROR] LITE(11206,converter_lite):2021-01-08-09:53:15.978.801 [mindspore/lite/tools/common/protobuf_utils.cc:94] ReadProtoFromBinaryFile] Parse ../../../../mindspore_mnist/checkpoint_lenet-1_1875.mindir failed.
[ERROR] LITE(11206,converter_lite):2021-01-08-09:53:15.979.004 [mindspore/lite/tools/anf_importer/import_from_mindir.cc:911] ReadOnnxFromBinary] Read onnx model file failed, which is not a matched onnx model
[WARNING] LITE(11206,converter_lite):2021-01-08-09:53:15.995.141 [mindspore/lite/tools/converter/legacy_optimizer/graph/tensor_name_pass.cc:39] Run] input tensor (id = 7) name is null
CONVERT RESULT SUCCESS:0

生成了checkpoint_lenet-1_1875.ms文件

**Comment by AssassinGQ** [comment]
模型已经转换成功，这个错误信息可以忽略。

**Comment by leonwanghui** [comment]
@gyr-kdgc If there is no other problem, please be free to close this issue, thanks!
