### ISSUE TITLE
Does Ascend910 support custom ops?

### ISSUE THREAD

**Issue by zjd1988** [mindspore-ai/mindspore#11]
I want not only to use Ascend910 inference network,and also want to implment some custom compute missions .

**Comment by kingxiaoxian** [comment]
By frozen model if you are referring to freezing and then[ restoring of the model](https://medium.com/@prasadpal107/saving-freezing-optimizing-for-inference-restoring-of-tensorflow-models-b4146deb21b5),  currently MindSpore supports frozen model via exporting to ONNX model for inference usage on backends like GPU. In addition, MindSpore supports load checkpoint with network resouce code on gpu, which is saved from training. You can get example from our [tutorial](https://www.mindspore.cn/tutorial/en/master/use/saving_and_loading_model_parameters.html.).

**Comment by kingxiaoxian** [comment]
MindSpore supports custom ops by following steps: 
1. Add op primitives; 
2. Implement op calculation logic; 
3. Register op basic information; 

A tutorial will be added in the furture.

**Comment by zjd1988** [comment]
@kingxiaoxian  thanks for your reply. It means Ascend910 just like nvidia GPU?

**Comment by hannibalhuang** [comment]
> @kingxiaoxian thanks for your reply. It means Ascend910 just like nvidia GPU?

Hi for detailed information regarding Ascend 910, you could refer to our [official website](https://e.huawei.com/se/products/cloud-computing-dc/atlas/ascend-910) :)
