### ISSUE TITLE
ResizeBilinear on GPU

### ISSUE THREAD

**Issue by BebDong** [mindspore-ai/mindspore#127]
I tried to re-implement the Deeplabv3 model on the NVIDIA GPU platform with MindSpore. However, I was surprised to find that the `ResizeBilinear` operation does not support the GPU platform. How should I solve this problem?

**Comment by cxl-ll** [comment]
Hello user, your question has also been mentioned in the mindspore forum. I'll give you a reply here. There is no plan to support GPU for the time being, but it should be supported by the end of June this year. Thank you.

**Comment by BebDong** [comment]
Thanks for the reply.
