### ISSUE TITLE
Unable to train PanGu1 model on MindSpore

### ISSUE THREAD

**Issue by amanwalia123** [mindspore-ai/mindspore#136]
## Background
Hi,

I am looking to try PanGu1 code [Link](https://github.com/mindspore-ai/mindspore/tree/r1.2/model_zoo/official/nlp/pangu1) for training on Mindspore, but couldn't find the dataset used for training. Can you please help me how to get the dataset?

## How to Fix
Please add link to the dataset used for training under [dataset](https://github.com/mindspore-ai/mindspore/tree/r1.2/model_zoo/official/nlp/pangu1#dataset).

**Comment by twoflypig** [comment]
Hi, sorry for the late reply. The dataset can be any corpus available on the Internet or some public dataset such as Wikipeadia and OpenWebText. Once the corpuse is ready, you can refer to [preprocess](https://github.com/mindspore-ai/mindspore/blob/master/model_zoo/official/nlp/gpt/src/pre_process.py) to generate mindrecord files for training. 

Hopefully this helps, feel free to ask questions.

**Comment by twoflypig** [comment]
Hi, as there is no response in six days and I will close the issuse, feel free to open this again if you meet any quetions.
