### ISSUE TITLE
'Dropout' object has no attribute 'dropout_gen_mask'

### ISSUE THREAD

**Issue by mymusise** [mindspore-ai/mindspore#137]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
- CPU: AMD 2950x
- GPU: not used

### Software Environment:
- **MindSpore version (source or binary)**: 1.2.0rc1
- **Python version (e.g., Python 3.7.5)**:  3.7.4
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04

I got an error when running the prediction script of [PanGu-Alpha ](https://git.openi.org.cn/PCL-Platform.Intelligence/PanGu-Alpha)
```
~/sources/PanGu-Alpha/pangu_alpha.py in __init__(self, config, scale, layer_idx)
    283         self.use_past = config.use_past
    284         self.dropout = nn.Dropout(1 - config.dropout_rate)
--> 285         self.dropout.dropout_gen_mask.shard(((config.dp, 1, 1),))
    286         self.dropout.dropout_do_mask.shard(((config.dp, 1, 1),))
    287         self.prob_dropout = nn.Dropout(1 - config.dropout_rate)

~/sources/PanGu-Alpha/env/lib/python3.7/site-packages/mindspore/nn/cell.py in __getattr__(self, name)
    264                 para_list = ParameterTuple(cast_list)
    265                 return para_list
--> 266         raise AttributeError("'{}' object has no attribute '{}'.".format(type(self).__name__, name))
    267 
    268     def __del__(self):

AttributeError: 'Dropout' object has no attribute 'dropout_gen_mask'.
```

Does `Dropout.dropout_gen_mask` has been remove in `1.2.0rc1` version?

**Comment by cxl-ll** [comment]
Mindpore Dropout does not have these two attributes on the front end.

**Comment by mymusise** [comment]
Got it, thank you, Guy.
