### ISSUE TITLE
x86 predict build error

### ISSUE THREAD

**Issue by liuchanchen** [mindspore-ai/mindspore#15]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:0.1
- **Python version (e.g., Python 3.7.5)**:Python 3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**: gcc 7.5

## Describe the current behavior
occurs build error:
CMake Error at src/CMakeLists.txt:56 (add_dependencies):
  The dependency target "securec" of target "mspredict" does not exist.
CMake Error at benchmark/CMakeLists.txt:34 (add_dependencies):
  The dependency target "securec" of target "benchmark" does not exist.
CMake Error at test/CMakeLists.txt:41 (add_dependencies):
  The dependency target "securec" of target "ms-test" does not exist.
CMake Error at module/tvm_kernel/lite/CMakeLists.txt:140 (add_dependencies):
  The dependency target "securec" of target "tvm_kernel" does not exist.

## Steps to reproduce the issue
1.  cd mindspore
2. ./build.sh -I x86_64 -j4

**Comment by quarter-3** [comment]
please retry building after removing 'build' directory, this rarely happens on x86 platform, we are working on fixing it.

**Comment by liuchanchen** [comment]
It seems be ok after I delete the depency of securec in CMake.txt

**Comment by quarter-3** [comment]
Thank you for the information.

**Comment by leonwanghui** [comment]
Hi @liuchanchen, could you close the issue if the question has been resolved? Thanks : )
