### ISSUE TITLE
编译MindSpore Lite r1.2 需要从GITHUB下载依赖包的问题

### ISSUE THREAD

**Issue by JeffDing** [mindspore-ai/mindspore#150]
在X86平台编译MindSpore r1.2需要多次从GITHUB下载依赖包，目前网络环境访问GITHUB经常会出现有时候能连上有时候连不上的情况。同时如果有一个包无法下载断掉后，再重新开始编译每次都要再把前面安装过的又重新下载了一次。

有没有办法实现编译过程中已经从github下载编译安装过的包，断掉后再重新开始编译的时候从断掉的那个包继续，或者编译过程中除了从GITHUB上下载包以外还有其他什么能稳定下载的方式吗？

**Comment by vzhanghaibo** [comment]
建议使用build.sh脚本里提供的-S选项，例如： ./build.sh -I x86_64 -S on
这样会从gitee提供的镜像上下载依赖包。

**Comment by JeffDing** [comment]
> 建议使用build.sh脚本里提供的-S选项，例如： ./build.sh -I x86_64 -S on
> 这样会从gitee提供的镜像上下载依赖包。

好的，谢了，我试试看
