### ISSUE TITLE
ModelArts运行Mindspore代码训练日志中的[EVENT]日志信息显示问题

### ISSUE THREAD

**Issue by JeffDing** [mindspore-ai/mindspore#152]
![image](https://user-images.githubusercontent.com/3302463/124057714-93695e00-da5a-11eb-8df2-53f0dbaf4051.png)  
在ModelArts运行MindSpore会出现类似这样的[Event]日志信息，有什么办法可以不显示吗？通过代码就可以实现还是需要找相关的工作人员？

**Comment by cxl-ll** [comment]
请设置os.environ["ASCEND_SLOG_PRINT_TO_STDOUT"]=0试试

**Comment by JeffDing** [comment]
> 请设置os.environ["ASCEND_SLOG_PRINT_TO_STDOUT"]=0试试

好的，谢了，好像可以了
