### ISSUE TITLE
CreateTensor

### ISSUE THREAD

**Issue by TsungchengWu** [mindspore-ai/mindspore#155]
如果我从**tensor1**创建**tensor2**时这么写，会不会使得两个 `tensor` 的 `data()` 指向同一块内存？
```
auto tensor2= tensor::MSTensor::CreateTensor(
                    tensor1->tensor_name(),
                    tensor1->data_type(),
                    tensor1->shape(),
                    tensor1->data(),
                    tensor1->Size()
            );
```

**Comment by Dcmdan** [comment]
tensor2 = CreateTensor(tensor1);
这样tensor1和tensor2是两个独立的tensor

tensor2 = CreateRefTensor(tensor2);
这样tensor1和tensor2指向同一块内存，tensor1持有所有权，tensor2仅仅引用，请注意如果tensor1走出作用域，tensor2会变成悬垂引用

**Comment by TsungchengWu** [comment]
> tensor2 = CreateTensor(tensor1);
> 这样tensor1和tensor2是两个独立的tensor
> 
> tensor2 = CreateRefTensor(tensor2);
> 这样tensor1和tensor2指向同一块内存，tensor1持有所有权，tensor2仅仅引用，请注意如果tensor1走出作用域，tensor2会变成悬垂引用

十分感谢，似乎Lite只支持CreateTensor，但也够用了。
