### ISSUE TITLE
value_and_grad 算子在linux上的1.8.0版本不存在

### ISSUE THREAD

**Issue by archersama** [mindspore-ai/mindspore#204]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>
> `/device gpu`</br>
> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:
- **Python version (e.g., Python 3.7.5)**:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:
- **GCC/Compiler version (if compiled from source)**: 

## Steps to reproduce the issue
1. 
2. 
3.

**Comment by cxl-ll** [comment]
https://www.mindspore.cn/docs/zh-CN/r1.8/api_python/ops/mindspore.ops.value_and_grad.html?highlight=value_and_grad#mindspore-ops-value-and-grad

**Comment by archersama** [comment]
I can use this ops in windows  mindspore1.8.0,  but in linux, i can't import this ops

**Comment by MindWilliam** [comment]
please check the mindspore version in linux? 
I did not reproduce this problem。
![image](https://user-images.githubusercontent.com/111826598/192077779-397cfedf-88e5-4acb-be50-6e52d4ba184d.png)

**Comment by archersama** [comment]
![image](https://user-images.githubusercontent.com/14331643/192078191-f18a5eb5-4fd3-439c-b5b8-e415a331627b.png)
mindspore :linux 1.8.0 cpu

**Comment by archersama** [comment]
solved
