### ISSUE TITLE
关于使用动态规划进行自动搜索并行策略的代码的问题

### ISSUE THREAD

**Issue by kevinsouthxu** [mindspore-ai/mindspore#205]
https://gitee.com/mindspore/mindspore/blob/master/mindspore/ccsrc/frontend/parallel/auto_parallel/edge_costmodel.cc 

请问在并行策略搜索中，在edge_costmodel中的GetCostList函数，我在遍历一条边的两个点时将不同的策略作为输入调用这个函数，但是发现得到的costlist有的size可能是1可能是0，理论上对于一条边来说，选择两个端点的不同策略时这条边的cost有对应不同的值，可是costlist的size=0就不符合这一理论了，所以是否能够解释下为何对于某些特定的两个端点的策略，该边调用的GetCostList的size等于0呢

**Comment by bisunny** [comment]
size等于0的情况就是说这条边的输入策略（前面算子的策略）和输出策略（后面算子的策略）没有对应的cost，这种情况可能发生在含有identity节点的边上。identity节点是参数对应的operatorInfo节点，并不是每一个参数都会生成identity，只有一个参数被两个以上的算子共用的时候才会产生。对于identity和被使用算子连成的边，只有这条边的两个策略相同才会有cost，因为参数和使用它的算子策略（切分）要一样，且两个共用它的算子策略要一样才行。所以这就有可能使得GetCostList返回的result size=0。
可以看下edge_costmodel中的InitEdgeCost函数，生成这种边的时候就有上述逻辑。

**Comment by kevinsouthxu** [comment]
> size等于0的情况就是说这条边的输入策略（前面算子的策略）和输出策略（后面算子的策略）没有对应的cost，这种情况可能发生在含有identity节点的边上。identity节点是参数对应的operatorInfo节点，并不是每一个参数都会生成identity，只有一个参数被两个以上的算子共用的时候才会产生。对于identity和被使用算子连成的边，只有这条边的两个策略相同才会有cost，因为参数和使用它的算子策略（切分）要一样，且两个共用它的算子策略要一样才行。所以这就有可能使得GetCostList返回的result size=0。 可以看下edge_costmodel中的InitEdgeCost函数，生成这种边的时候就有上述逻辑。

非常感谢！现在我明白了！
