### ISSUE TITLE
What is the difference of relu/v2/v3 ? 

### ISSUE THREAD

**Issue by MARD1NO** [mindspore-ai/mindspore#206]
I found Mindspore has relu/relu_v2/relu_v3, what is the difference？

**Comment by cxl-ll** [comment]
Hello.What version of MindSpore is used? Reluv3 is not found in the latest version.

**Comment by MARD1NO** [comment]
> Hello.What version of MindSpore is used? Reluv3 is not found in the latest version.

I just saw some code in here: https://github.com/mindspore-ai/mindspore/blob/master/mindspore/core/ops/relu_v3.cc

**Comment by MindWilliam** [comment]
> 
reluv2 is deprecated, ReluV3 is a inner ops ，is not an exposed interface.

**Comment by MARD1NO** [comment]
> is not an exposed interface

thanks
