### ISSUE TITLE
Mindspore build with docker image failed 

### ISSUE THREAD

**Issue by ligc** [mindspore-ai/mindspore#21]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
`/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: source
- **Python version (e.g., Python 3.7.5)**: Python 
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: docker image Ubuntu 18.04.4, host os Ubuntu 16.04.5
- **GCC/Compiler version (if compiled from source)**:  7.5.0

## Describe the current behavior
Build mindspore with docker image mindspore/mindspore-cpu:0.1.0-alpha failed

```
root@mindspore:/mindspore# ./build.sh -e cpu -j 4
...
...
-- Configuring done
-- Generating done
-- Build files have been written to: /mindspore/build/mindspore/_deps/sqlite-subbuild
[100%] Built target sqlite-populate
sqlite_SOURCE_DIR : /mindspore/build/mindspore/_deps/sqlite-src
patching /mindspore/build/mindspore/_deps/sqlite-src -p1 < /mindspore/third_party/patch/sqlite/sqlite.patch001
patching file manifest
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
5 out of 5 hunks ignored -- saving rejects to file manifest.rej
patching file manifest.uuid
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file manifest.uuid.rej
patching file src/expr.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/expr.c.rej
patching file src/sqliteInt.h
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/sqliteInt.h.rej
patching file src/whereexpr.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
3 out of 3 hunks ignored -- saving rejects to file src/whereexpr.c.rej
CMake Error at cmake/utils.cmake:221 (message):
  Failed patch: /mindspore/third_party/patch/sqlite/sqlite.patch001
Call Stack (most recent call first):
  cmake/external_libs/sqlite.cmake:7 (mindspore_add_pkg)
  cmake/mind_expression.cmake:54 (include)
  CMakeLists.txt:17 (include)


-- Configuring incomplete, errors occurred!
See also "/mindspore/build/mindspore/CMakeFiles/CMakeOutput.log".
See also "/mindspore/build/mindspore/CMakeFiles/CMakeError.log".
root@mindspore:/mindspore# 
```

## Describe the expected behavior
Being able to build mindspore with the docker image

## Steps to reproduce the issue
1.  Run command ```docker run -it -v /root/mindspore:/mindspore --network=host mindspore/mindspore-cpu:0.1.0-alpha /bin/bash``` to start the build container
2.  Run command ```cd minspore; ./build.sh -e cpu -j4``` to start the build process

**Comment by leonwanghui** [comment]
Hi @ligc, the `mindspore/mindspore-cpu:0.1.0-alpha` has already installed MindSpore, therefore no need to compile the project again from the source code, you can directly try it with:
```
docker run -it --network=host mindspore/mindspore-cpu:0.1.0-alpha /bin/bash
python -c 'import mindspore'
```

For the details of how MindSpore docker images being generated, please take a look at https://github.com/mindspore-ai/mindspore/tree/master/docker.

**Comment by leonwanghui** [comment]
Another thing to be noticed is if you want to compile the project from the source, please make sure your software environment is the same with the [install requirements](https://www.mindspore.cn/install/en).

**Comment by ligc** [comment]
@leonwanghui  Thanks for the comments.  I was not aware that the docker image already has mindspore installed, I was taking the docker image as a build environment after struggling to build Mindspore on the host Ubuntu 16.04.  Will refer to the procedure in Dockerfile to setup the build environment on Ubuntu 16.04
