### ISSUE TITLE
Is it possible to have the `converter_lite` tool take a `.ms` file as input?

### ISSUE THREAD

**Issue by KB5201314** [mindspore-ai/mindspore#212]
I am working on building a tool based on `converter_lite`, which will:
1. Take a `.ms` model file as input
2. Apply some modifications to the input model, with the help of the `PassRegistry` extension.
3. Export it to another `.ms` model. 

I would like to know: is it possible to make `converter_lite` take a model in `ModelType.MINDIR_LITE` format (a.k.a. a `.ms` model) as input? If so, where should I start?

**Comment by cxl-ll** [comment]
Hello and welcome to MindSpore. Your question above is being confirmed, will give you an answer as soon as possible.

**Comment by 22dimensions** [comment]
converter_lite doesn't support taking .ms file as input, but you can still add a pass to modify the input model, these passes accept a FuncGraph data structure, you can refer to https://www.mindspore.cn/lite/docs/zh-CN/master/use/converter_register.html and some built-in passes under mindspore/lite/tools/optimizer directory.

**Comment by KB5201314** [comment]
> converter_lite doesn't support taking .ms file as input, but you can still add a pass to modify the input model, these passes accept a FuncGraph data structure, you can refer to https://www.mindspore.cn/lite/docs/zh-CN/master/use/converter_register.html and some built-in passes under mindspore/lite/tools/optimizer directory.

Thank you for your reply. Yes, converter_lite cannot take .ms file as input. I am trying to convert the .ms file to a FuncGraph object so that i can write a pass to modify it. I tried to find some functions similar to [`FuncGraphPtr ImportMindIR(const std::shared_ptr<ConverterPara> &param);`](https://github.com/mindspore-ai/mindspore/blob/d6d4235fa8173dc7a8476598a3435c7096cc53c3/mindspore/lite/tools/converter/import/mindspore_importer.h#L33) so that I can write a importer for .ms, but I didn't find anything.

Can you give me some advice? Or is there a way to convert .ms back to .mindir so I don't need to write an importer?

**Comment by 22dimensions** [comment]
The converter_lite first parses (ONNX/CAFFE/TF/TFLITE/MINDIR) model to FuncGraph, after some built-in and external passes, then converts optimized FuncGraph to .ms file. You can just add a pass to modify FuncGraph, then it will generate .ms file you want. So you don't need to write a importer for .ms. I am not sure it solve your problem.

**Comment by 22dimensions** [comment]
> > converter_lite doesn't support taking .ms file as input, but you can still add a pass to modify the input model, these passes accept a FuncGraph data structure, you can refer to https://www.mindspore.cn/lite/docs/zh-CN/master/use/converter_register.html and some built-in passes under mindspore/lite/tools/optimizer directory.
> 
> Thank you for your reply. Yes, converter_lite cannot take .ms file as input. I am trying to convert the .ms file to a FuncGraph object so that i can write a pass to modify it. I tried to find some functions similar to [`FuncGraphPtr ImportMindIR(const std::shared_ptr<ConverterPara> &param);`](https://github.com/mindspore-ai/mindspore/blob/d6d4235fa8173dc7a8476598a3435c7096cc53c3/mindspore/lite/tools/converter/import/mindspore_importer.h#L33) so that I can write a importer for .ms, but I didn't find anything.
> 
> Can you give me some advice? Or is there a way to convert .ms back to .mindir so I don't need to write an importer?

The converter_lite first parses (ONNX/CAFFE/TF/TFLITE/MINDIR) model to FuncGraph, after some built-in and external passes, then converts optimized FuncGraph to .ms file. You can just add a pass to modify FuncGraph, then it will generate .ms file you want. So you don't need to write a importer for .ms. I am not sure it solve your problem.

**Comment by KB5201314** [comment]
> > > converter_lite doesn't support taking .ms file as input, but you can still add a pass to modify the input model, these passes accept a FuncGraph data structure, you can refer to https://www.mindspore.cn/lite/docs/zh-CN/master/use/converter_register.html and some built-in passes under mindspore/lite/tools/optimizer directory.
> > 
> > 
> > Thank you for your reply. Yes, converter_lite cannot take .ms file as input. I am trying to convert the .ms file to a FuncGraph object so that i can write a pass to modify it. I tried to find some functions similar to [`FuncGraphPtr ImportMindIR(const std::shared_ptr<ConverterPara> &param);`](https://github.com/mindspore-ai/mindspore/blob/d6d4235fa8173dc7a8476598a3435c7096cc53c3/mindspore/lite/tools/converter/import/mindspore_importer.h#L33) so that I can write a importer for .ms, but I didn't find anything.
> > Can you give me some advice? Or is there a way to convert .ms back to .mindir so I don't need to write an importer?
> 
> The converter_lite first parses (ONNX/CAFFE/TF/TFLITE/MINDIR) model to FuncGraph, after some built-in and external passes, then converts optimized FuncGraph to .ms file. You can just add a pass to modify FuncGraph, then it will generate .ms file you want. So you don't need to write a importer for .ms. I am not sure it solve your problem.

Thank you, I've switched to importing .mindir file, and it looks good so far.
