### ISSUE TITLE
resnet50 traning error on cpu using offical example

### ISSUE THREAD

**Issue by liuchanchen** [mindspore-ai/mindspore#22]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:0.1
- **Python version (e.g., Python 3.7.5)**:Python 3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**: gcc 7.5.0

## Describe the current behavior
I try to execute example/resnet50_cifar10/training.py, the the error log shows " BiasAddGrad input y backprop, dim should >= 2, while 1". It seems like the errors in the process of constructing graph.

## Describe the expected behavior
no errors

## Steps to reproduce the issue
1. download cifar10-binary
2. export DEVICE_NUM=1 in bash
3. export RANK_ID=1 in bash
4. chang the default dataset path to mine path
5. set device_target='CPU'
6. set enable_loop_sink=False
7. pass 'dataset_sink_mode=False ' to model.train
8. python ./train.py

## Related log / screenshot
[ERROR] ME(32429,python):2020-04-03-10:53:16.561.678 [mindspore/ccsrc/operator/prim_nn.cc:258] InferImplBiasAddGrad] BiasAddGrad input y backprop, dim should >= 2, while 1.
Traceback (most recent call last):
  File "train.py", line 99, in <module>
    model.train(epoch_size, dataset, callbacks=cb,dataset_sink_mode=False)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/train/model.py", line 387, in train
    dataset_sink_mode=dataset_sink_mode)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/train/model.py", line 230, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/train/model.py", line 324, in _train_process
    outputs = self._train_network(*next_element)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/nn/cell.py", line 141, in __call__
    out = self.compile_and_run(*inputs)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/nn/cell.py", line 292, in compile_and_run
    _, compile_flag = _executor.compile(self, *inputs, phase=self.phase)
  File "/home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/common/api.py", line 363, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/operator/prim_nn.cc:258 InferImplBiasAddGrad] BiasAddGrad input y backprop, dim should >= 2, while 1.
The function call stack:
0  In file /home/jianliu/anaconda3/envs/mindspore_env/lib/python3.7/site-packages/mindspore/nn/wrap/cell_wrapper.py(64)
    def construct(self, data, label):

**Comment by liuchanchen** [comment]
Does the current version supports training resnet50 ? I notice the readme shows not supporting [](https://github.com/mindspore-ai/mindspore/blob/master/RELEASE.md)

**Comment by leonwanghui** [comment]
Hi @liuchanchen, currently there are limited models supported in MindSpore with `CPU` and `GPU` backend, but we are working on improving it (see [MindSpore Roadmap](https://www.mindspore.cn/docs/en/master/roadmap.html#inference-framework)).
