### ISSUE TITLE
呵呵，菊花厂先违规喽

### ISSUE THREAD

**Issue by ghost** [mindspore-ai/mindspore#228]
http://www.cac.gov.cn/2023-04/11/c_1682854275475410.htm

**Comment by JOY-SWang** [comment]
没懂。省流：链接内容是《国家互联网信息办公室关于《生成式人工智能服务管理办法（征求意见稿）》公开征求意见的通知》，并未提及谁违不违规啊

**Comment by GoddessLuBoYan** [comment]
第三条 国家支持人工智能算法、框架等基础技术的自主创新、推广应用、国际合作，鼓励优先采用安全可信的软件、工具、计算和数据资源。

国家鼓励与支持啊

**Comment by hd24007** [comment]
黑也要遵循基本法，naive

**Comment by MGLSIDE** [comment]
> 没懂。省流：链接内容是《国家互联网信息办公室关于《生成式人工智能服务管理办法（征求意见稿）》公开征求意见的通知》，并未提及谁违不违规啊

请您把您的工资作为违法收入，自觉上缴。

**Comment by GoddessLuBoYan** [comment]
> > 没懂。省流：链接内容是《国家互联网信息办公室关于《生成式人工智能服务管理办法（征求意见稿）》公开征求意见的通知》，并未提及谁违不违规啊
> 
> 请您把您的工资作为违法收入，自觉上缴。

不好意思，我的是合法的，上了税和社保的

**Comment by GoddessLuBoYan** [comment]
有没有管理员管一下这个issue，把它关掉

**Comment by MGLSIDE** [comment]
> > > 没懂。省流：链接内容是《国家互联网信息办公室关于《生成式人工智能服务管理办法（征求意见稿）》公开征求意见的通知》，并未提及谁违不违规啊
> > 
> > 
> > 请您把您的工资作为违法收入，自觉上缴。
> 
> 不好意思，我的是合法的，上了税和社保的

请君自看:https://m.dw.com/zh/%E6%89%BF%E5%BE%B7%E7%A8%8B%E5%BA%8F%E5%91%98%E7%BF%BB%E5%A2%99%E8%A2%AB%E6%B2%A1%E6%94%B6%E7%99%BE%E4%B8%87%E4%BD%99%E5%85%83%E6%94%B6%E5%85%A5-it%E5%9C%88%E9%9C%87%E6%83%8A/a-66928286

**Comment by LitePlan** [comment]
你好，社区主要以讨论技术问题为主，非技术问题不建议在讨论，感谢大家的参与，本ISSUE关闭。
