### ISSUE TITLE
端侧推理，https://github.com/mindspore-ai/mindspore/tree/master/predict目录下代码只是支持端侧的推理吧？

### ISSUE THREAD

**Issue by zjd1988** [mindspore-ai/mindspore#23]
如果要看GPU的推理，可以看哪部分代码呢？暂时还没看到如何自定义增加op的文档。

**Comment by leonwanghui** [comment]
Hi @zjd1988, as you said, the predict module is designed to perform model prediction on mobile device. If you want to predict model on GPU, currently you can export model to ONNX (see [export API usage](https://www.mindspore.cn/api/zh-CN/master/api/python/mindspore/mindspore.train.html#mindspore.train.serialization.export)), then perform ONNX model with GPU runtimes (such as TensorRT).

**Comment by zjd1988** [comment]
@leonwanghui  ok, thanks for reply. I check mindspore source code,and find cuda kernels.Is there any c++ examples about inference network with these cuda kernels?

**Comment by leonwanghui** [comment]
@zjd1988 Sorry for the delay, currently only evaluation is supported using these GPU kernels you mentioned, so ONNX is suggested to convert when you want to use TensorRT to inference MindSpore model.

**Comment by zjd1988** [comment]
@leonwanghui  appreciate it. Does Mindspore has plan to support predict with GPU?

**Comment by leonwanghui** [comment]
@zjd1988 Could you explain a bit for what predict runtime you want to use? If you are using TensorRT for model predict, then it's not supported for the short term; But if you just want to test predict function on MindSpore, you could call [`Model.predict()`](https://www.mindspore.cn/api/zh-CN/master/api/python/mindspore/mindspore.html#mindspore.Model) function to perform model prediction on GPU.

**Comment by zjd1988** [comment]
Hi @leonwanghui ,thanks for your reply. I just want to predict with mindspore c++ api (using GPU kernels) , not with python api. and will Mindspore  plan to inference with GPU by self c++  api, not using tensorrt.

**Comment by leonwanghui** [comment]
@zjd1988 I see, if you are referring the C++ API support of MindSpore, then we are already planning to work on it, we will keep you informed when the design plan is published.

**Comment by zjd1988** [comment]
@leonwanghui  looking forward it!!!

**Comment by wangh09** [comment]
looking forward to the inference engine too !!!!!!!! gpu & cpu
