### ISSUE TITLE
Seeking support for Concat() operation in mindspore CPU

### ISSUE THREAD

**Issue by ID56** [mindspore-ai/mindspore#24]
**Device:** CPU
**OS:** Ubuntu 18.04.04 LTE
**Mindspore Version:** 0.1.0-alpha
**Installation:** Installed with pip from the wheel - https://ms-release.obs.cn-north-4.myhuaweicloud.com/0.1.0-alpha/MindSpore/cpu/ubuntu-x86/mindspore-0.1.0-cp37-cp37m-linux_x86_64.whl

Hello. I've just started using MindSpore, and I really like it thus far. However, I ran into a problem: When I attempt to use the Concat() operation from _mindspore.ops.operations.Concat()_, it raises a NotImplementedError. This leads to me thinking that Concat() is not yet included in the CPU version of mindspore? I'd like to know if Concat() will be available for CPU soon. Or if it is included in the gpu release, then I may also shift to the cuda installation.

Thanks in advance!

**Comment by leonwanghui** [comment]
Hi @ID56 , thanks for your feedback. For your question, the answer is currently `Concat` operator is supported on GPU and Ascend device and CPU support is on the way. For the operator support matrix, please see https://www.mindspore.cn/docs/en/master/operator_list.html for details.

**Comment by ID56** [comment]
Alright, thanks a lot.
