### ISSUE TITLE
how to quantize a fp32 model

### ISSUE THREAD

**Issue by liuchanchen** [mindspore-ai/mindspore#25]
Are there some tools for quantization in mindspore? Could you tell me some docs about mindspore quantization if they existed.

**Comment by leonwanghui** [comment]
Hi @liuchanchen , thanks for pulling this issue. Currently MindSpore doesn't support quantization on trained model, but we are working on it.

**Comment by liuchanchen** [comment]
> Hi @liuchanchen , thanks for pulling this issue. Currently MindSpore doesn't support quantization on trained model, but we are working on it.

Thanks for reply

**Comment by leonwanghui** [comment]
@liuchanchen Please close the issue if the question being resolved, thx : )
