### ISSUE TITLE
comp/runtime

### ISSUE THREAD

**Issue by liuainlp** [mindspore-ai/mindspore#252]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>

### Software Environment:
- **MindSpore version (2.2.0)**:
- **Python version (Python 3.8.18)**:
- **OS platform and distribution (Linux Ubuntu Ubuntu 20.04.4 LTS)**:
- **GCC/Compiler version (5.4.0-100-generic)**: 

## Describe the current behavior
Ascend 3001 pro推理卡，Cann版本：7.0.Rc1；
npu-smi info检查正常，ascend-dmi -c 检查正常；
多卡推理构建hccl_4p_0123_127.0.0.1.json文件时报错：
start ../../mindformers/tools/hccl_tools.py
visible_devices:['0', '1', '2', '3', '4', '5', '6', '7']
server_id:127.0.1.1
device_num_list: [0, 1, 2, 3]
/bin/sh: 1: hccn_tool: not found
Failed to call hccn_tool, try to read /etc/hccn.conf instead
Traceback (most recent call last):
  File "../../mindformers/tools/hccl_tools.py", line 163, in <module>
    main()
  File "../../mindformers/tools/hccl_tools.py", line 137, in main
    device_ip = device_ips[device_id]
KeyError: '0'

## Describe the expected behavior
当前环境可创建hccl_4p_0123_127.0.0.1.json策略文件；
实现模型推理

## Steps to reproduce the issue
1. Wizardcoder_15B在Ascend 3001 pro推理卡四卡推理

## Related log / screenshot
![image](https://github.com/mindspore-ai/mindspore/assets/105497144/d92668a3-f5f1-4ef8-8068-cb6b1489bfaa)

## Special notes for this issue
能否提供Ascend 3001 pro推理卡，mindspore==2.2.0环境搭建版本参数和流程

**Comment by cxl-ll** [comment]
Hello, welcome to MindSpore. Based on your question, it is recommended that you try the model reasoning tutorial on the official website.
https://www.mindspore.cn/tutorials/experts/zh-CN/r2.2/infer/inference.html
If you have any questions, you can also ask questions in gitee.
https://gitee.com/mindspore/mindspore/issues
