### ISSUE TITLE
ubuntu22.4安装好GPU版本2.1.0后不能使用GPU

### ISSUE THREAD

**Issue by xiongfazhan** [mindspore-ai/mindspore#253]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device gpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:2.1.0
- **Python version (e.g., Python 3.7.5)**:3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 22.04
- **GCC/Compiler version (if compiled from source)**: 7/8

## Describe the current behavior
(mindspore_py37) ***:~/mindyolo$ python -c "import mindspore;mindspore.set_context(device_target='GPU');mindspore.run_check()"
MindSpore version:  2.1.0
The result of multiplication calculation is correct, MindSpore has been installed on platform [GPU] successfully!
[ERROR] DEVICE(2382696,7fe93dd0b740,python):2023-11-28-21:28:17.917.989 [mindspore/ccsrc/runtime/pynative/async/async_queue.cc:232] WorkerJoin] WorkerJoin failed: 
----------------------------------------------------
- Cuda error:
----------------------------------------------------
The cudaStreamCreateWithFlags failed, ret[2], out of memory

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/plugin/device/gpu/hal/device/cuda_driver.cc:182 CreateStream

[ERROR] ME(2382696,7fe93dd0b740,python):2023-11-28-21:28:17.918.038 [mindspore/ccsrc/runtime/hardware/device_context_manager.cc:541] WaitTaskFinishOnDevice] SyncStream failed

## Describe the expected behavior
不知道是什么原因

**Comment by cxl-ll** [comment]
Hello, welcome to MindSpore. Here is a message indicating that your memory is insufficient. It is recommended that you clean up the content and try again.
