### ISSUE TITLE
fft

### ISSUE THREAD

**Issue by SecretLittleBoy** [mindspore-ai/mindspore#254]
## Background
做从pytorch到mindSpore的模型迁移，遇到了`query_states_fft = torch.fft.rfft(query_states, n=tgt_len, dim=1)` `attn_weights = torch.fft.irfft(attn_weights, n=tgt_len, dim=1)`，mindSpore中没有合适的对应API
## Introduction
rfft(input, n=None, dim=-1, norm=None, *, out=None) -> Tensor
Computes the one dimensional Fourier transform of real-valued :attr:`input`.
Args:
    input (Tensor): the real input tensor
    n (int, optional): Signal length. If given, the input will either be zero-padded
        or trimmed to this length before computing the real FFT.
    dim (int, optional): The dimension along which to take the one dimensional real FFT.
    norm (str, optional): Normalization mode. 

## Trail
| No. | Task Description | Related Issue(URL) |
| --- | ---------------- | ------------------ |
| 1   |                  |                    |
| 2   |                  |                    |

**Comment by cxl-ll** [comment]
Sorry, MindSpore does not have this operator. You are advised to submit a requirement at the following link:https://gitee.com/mindspore/mindspore/issues
