### ISSUE TITLE
mindspore有清理显存的函数吗

### ISSUE THREAD

**Issue by datalee** [mindspore-ai/mindspore#255]
如题，类似gpu的这种
![image](https://github.com/mindspore-ai/mindspore/assets/13651873/fdc3403f-3472-41f8-8192-973f2c3f62bc)

**Comment by cxl-ll** [comment]
Hello. Currently, there is no interface for clearing the video buffer, but there are optimized interfaces:https://www.mindspore.cn/tutorials/experts/zh-CN/r2.2/parallel/optimize_technique.html

**Comment by datalee** [comment]
> Hello. Currently, there is no interface for clearing the video buffer, but there are optimized interfaces:https://www.mindspore.cn/tutorials/experts/zh-CN/r2.2/parallel/optimize_technique.html

ok，thanks
