### ISSUE TITLE
mindsporelite源码编译报错fatal error: Python.h: No such file or directory

### ISSUE THREAD

**Issue by lingxiao520** [mindspore-ai/mindspore#257]
使用docker pull swr.cn-south-1.myhuaweicloud.com/mindspore-build/mindspore-lite:ubuntu18.04.2-20210530镜像
进行mindspore编译
报错如下：
[ 93%] Building CXX object minddata/CMakeFiles/minddata-lite-obj.dir/home/mindspore/mindspore/ccsrc/minddata/dataset/util/intrp_service.cc.o
[ 93%] Building CXX object minddata/CMakeFiles/minddata-lite-obj.dir/home/mindspore/mindspore/ccsrc/minddata/dataset/util/arena.cc.o
[ 93%] Built target minddata-lite-obj
start get operator mapping file prototype
start get operator mapping file prototype
start get operator mapping file kNumberTypeFloat32
start get operator mapping file kNumberTypeFloat16
start get operator mapping file kNumberTypeInt8
start get operator mapping file kNumberTypeInt32
start get operator mapping file kNumberTypeInt32
start get operator mapping nnacl kernel kNumberTypeFloat32
start get operator mapping nnacl kernel kNumberTypeFloat16
start get operator mapping nnacl kernel kNumberTypeInt8
start get operator mapping nnacl kernel kNumberTypeInt32
start get operator mapping nnacl kernel kNumberTypeInt32
start get operator mapping nnacl kernel kNumberTypeFloat32
start get operator mapping nnacl kernel kNumberTypeFloat16
start get operator mapping nnacl kernel kNumberTypeInt8
start get operator mapping nnacl kernel kNumberTypeInt32
start get operator mapping nnacl kernel kNumberTypeInt32
start get gpu/npu operator mapping file kNumberTypeFloat32
start get gpu/npu operator mapping file kNumberTypeFloat16
start get gpu/npu operator mapping file kNumberTypeInt8
start get gpu/npu operator mapping file kNumberTypeInt32
start get gpu/npu operator mapping file kNumberTypeInt32
Complete all tasks.
[ 93%] Built target cropper
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2
[  0%] Built target schema_gen
[  0%] Built target gen_ops
[  0%] Built target fbs_src
[  1%] Built target fbs_inner_src
[  3%] Built target securec
[  4%] Built target proto_mid
[  4%] Building CXX object tools/converter/CMakeFiles/ccsrc_src_mid.dir/home/mindspore/mindspore/ccsrc/utils/anfalgo.cc.o
In file included from /usr/local/include/pybind11/attr.h:13:0,
                 from /usr/local/include/pybind11/detail/class.h:12,
                 from /usr/local/include/pybind11/pybind11.h:13,
                 from /home/mindspore/mindspore/ccsrc/pybind_api/ir/primitive_py.h:29,
                 from /home/mindspore/mindspore/ccsrc/utils/anfalgo.cc:37:
/usr/local/include/pybind11/detail/common.h:274:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
tools/converter/CMakeFiles/ccsrc_src_mid.dir/build.make:146: recipe for target 'tools/converter/CMakeFiles/ccsrc_src_mid.dir/home/mindspore/mindspore/ccsrc/utils/anfalgo.cc.o' failed
make[2]: *** [tools/converter/CMakeFiles/ccsrc_src_mid.dir/home/mindspore/mindspore/ccsrc/utils/anfalgo.cc.o] Error 1
CMakeFiles/Makefile2:1005: recipe for target 'tools/converter/CMakeFiles/ccsrc_src_mid.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/ccsrc_src_mid.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KevinKaChunLee** [comment]
看起来你没有安装python头文件。如果你正在使用ubuntu，你可以尝试运行sudo apt-get install python3-dev来安装
