### ISSUE TITLE
MindSporeLite 加载CLIP模型报错

### ISSUE THREAD

**Issue by ycw66** [mindspore-ai/mindspore#261]
### 硬件环境
- **Target device: CPU**
- *CPU arch: x86_64*

### 软件环境
- **MindSporeLite version: 2.2.11**:
- **Python version: 3.7.12**:
- **OS platform and distribution: Linux Ubuntu 23.04**

## 当前行为
通过mindspore-lite python API加载ms格式的CLIP模型报错，报错信息如下：
```
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.987.997 [mindspore/lite/src/litert/scheduler.cc:873] InferSubGraphShape] InferShape failed, name: /visual/transformer/resblocks/resblocks.0/attn/Reshape_2, type: Reshape
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.013 [mindspore/lite/src/litert/scheduler.cc:237] SchedulePreProcess] op infer shape failed.
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.078 [mindspore/lite/src/litert/lite_session.cc:608] CompileGraph] Schedule kernels failed: -500
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.136 [mindspore/lite/src/litert/lite_session.cc:2066] LoadModelAndCompileByBuf] Compile model failed
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.177 [mindspore/lite/src/extendrt/delegate/graph_executor/litert/graph_executor.cc:100] CompileGraph] Load model by meta graph failed
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.182 [mindspore/lite/src/extendrt/session/delegate_session.cc:60] CompileGraph] GraphSinkSession::CompileGraph compile graph failed
[ERROR] ME(1553789,7f2e4f691740,python):2024-02-23-13:17:47.988.189 [mindspore/lite/src/extendrt/cxx_api/model/model_impl.cc:382] BuildByBufferImpl] compile graph failed.
Traceback (most recent call last):
  File "produce_bug.py", line 18, in <module>
    clip_model.build_from_file(MODEL_PATH, mslite.ModelType.MINDIR_LITE, context)
  File "/home/weggle/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore_lite/model.py", line 111, in wrapper
    return func(*args, **kwargs)
  File "/home/weggle/miniconda3/envs/mindspore/lib/python3.7/site-packages/mindspore_lite/model.py", line 263, in build_from_file
    f"build_from_file failed! Error is {ret.ToString()}")
RuntimeError: build_from_file failed! Error is Common error code.
```
## 期望行为
能够使用mindspore-lite python API成功加载ms格式的CLIP模型，并且后续可以正常执行推理。

## 复现
1. 使用python pytorch API将CLIP模型采用ONNX格式导出
2. 使用mindspore提供的converter 将导出的ONNX格式模型转换成ms格式
3. 通过python mindspore lite API 加载转换后的ms格式的CLIP模型

**Comment by Ash-Lee233** [comment]
您好，ONNX的CLIP模型和python API加载ms格式的CLIP模型的代码链接能提供下吗

**Comment by ycw66** [comment]
# 补充复现细节
1. CLIP Model通过以下代码导出
> CLIP模型文件太大了无法放到附件，可以通过以下代码导出，代码中用到的图片pokemon.jpeg如下：
![pokemon](https://github.com/mindspore-ai/mindspore/assets/46104495/5695a1b3-670b-4d50-b4fc-56f05e673f23)
``` python
import torch 
from PIL import Image

import cn_clip.clip as clip
from cn_clip.clip import load_from_name, available_models
print("Available models:", available_models())  
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = load_from_name("ViT-B-16", device=device, download_root='./')
model.eval()
image = preprocess(Image.open("pokemon.jpeg")).unsqueeze(0).to(device)
text = clip.tokenize(["皮卡丘"]).to(device)
torch.onnx.export(model, (image.type, text), "Clip.onnx")
```
2. 使用mindspore提供的converter 将导出的ONNX格式模型转换成ms格式
```
./converter_lite --fmk=ONNX --modelFile=/path/to/Clip.onnx --outputFile=/path/to/Clip --saveType=MINDIR_LITE
```
3. 通过python mindspore lite API 加载转换后的ms格式的CLIP模型
> 加载ms格式的CLIP模型会报错。
``` python
import numpy as np
import mindspore_lite as mslite
import torch 
from PIL import Image
import cn_clip.clip as clip
from cn_clip.clip import load_from_name, available_models
import mindspore_lite as mslite

# init context, and set target is cpu
context = mslite.Context()
context.target = ["cpu"]
context.cpu.thread_num = 1
context.cpu.thread_affinity_mode=2

MODEL_PATH = "./Clip.ms"
# Load the encoder model
clip_model = mslite.Model()
clip_model.build_from_file(MODEL_PATH, mslite.ModelType.MINDIR_LITE, context)
```

**Comment by ycw66** [comment]
> 您好，ONNX的CLIP模型和python API加载ms格式的CLIP模型的代码链接能提供下吗

您好，补充的细节见以上的回复

**Comment by Ash-Lee233** [comment]
正在协调相关专家为您解答

**Comment by Greatpanc** [comment]
您好，
![image](https://github.com/mindspore-ai/mindspore/assets/38004594/87061873-ba30-4f88-8dc1-655a0fb4729e)
您这边用的torch版本是什么时候的？

**Comment by ycw66** [comment]
> 您好， ![image](https://private-user-images.githubusercontent.com/38004594/309218090-87061873-ba30-4f88-8dc1-655a0fb4729e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTM0MTMsIm5iZiI6MTcwOTI5MzExMywicGF0aCI6Ii8zODAwNDU5NC8zMDkyMTgwOTAtODcwNjE4NzMtYmEzMC00Zjg4LThkYzEtNjU1YTBmYjQ3MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDExMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjQzMTFkMTBlM2I0ZTQwODU0NTQzNjJiYTlmNjM1ZTVmZDU3NjI5Y2IzZTYyMDZkODI4ZWM0MDM2NTE4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mhMc2cfTMbmPtHPKuAYtnIPEokj3tLDqz5WB6P5GyZY) 您这边用的torch版本是什么时候的？

补充信息：
Pytorch version: 1.13.1
Device type: cpu

**Comment by Greatpanc** [comment]
> > 您好， ![image](https://private-user-images.githubusercontent.com/38004594/309218090-87061873-ba30-4f88-8dc1-655a0fb4729e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTM0MTMsIm5iZiI6MTcwOTI5MzExMywicGF0aCI6Ii8zODAwNDU5NC8zMDkyMTgwOTAtODcwNjE4NzMtYmEzMC00Zjg4LThkYzEtNjU1YTBmYjQ3MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDExMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjQzMTFkMTBlM2I0ZTQwODU0NTQzNjJiYTlmNjM1ZTVmZDU3NjI5Y2IzZTYyMDZkODI4ZWM0MDM2NTE4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mhMc2cfTMbmPtHPKuAYtnIPEokj3tLDqz5WB6P5GyZY) 您这边用的torch版本是什么时候的？
> 
> 补充信息： Pytorch version: 1.13.1 Device type: cpu

您好，我这边环境还是跑不起来, 您这边可以帮忙提供一下：
1、debug级别的日志嘛？export GLOG_v=0
2、reshape前后的网络结构图：visual/transformer/resblocks/resblocks.0/attn/Reshape_2
吗？谢谢了！

**Comment by ycw66** [comment]
> > > 您好， ![image](https://private-user-images.githubusercontent.com/38004594/309218090-87061873-ba30-4f88-8dc1-655a0fb4729e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTM0MTMsIm5iZiI6MTcwOTI5MzExMywicGF0aCI6Ii8zODAwNDU5NC8zMDkyMTgwOTAtODcwNjE4NzMtYmEzMC00Zjg4LThkYzEtNjU1YTBmYjQ3MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDExMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjQzMTFkMTBlM2I0ZTQwODU0NTQzNjJiYTlmNjM1ZTVmZDU3NjI5Y2IzZTYyMDZkODI4ZWM0MDM2NTE4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mhMc2cfTMbmPtHPKuAYtnIPEokj3tLDqz5WB6P5GyZY) 您这边用的torch版本是什么时候的？
> > 
> > 
> > 补充信息： Pytorch version: 1.13.1 Device type: cpu
> 
> 您好，我这边环境还是跑不起来, 您这边可以帮忙提供一下： 1、debug级别的日志嘛？export GLOG_v=0 2、reshape前后的网络结构图：visual/transformer/resblocks/resblocks.0/attn/Reshape_2 吗？谢谢了！

1. 请问您跑不起来python脚本的报错是什么呢？
2. 我提供一个导出的onnx格式的CLIP模型，你可以参考

**Comment by Greatpanc** [comment]
您好这个问题已经定位出来了，是因为有个优化pass将int类型计算换成了float类型计算导致slice出来的shape与reshape中指定的shape不匹配导致infershape报错，这个问题在我们近期的版本里面已经修复了，您可以关注我们近期版本的发布。
