### ISSUE TITLE
【建议】针对算子易用性问题，比如range函数，其三个参数的含义明明就是3个数值，这里非得要求你传入3个张量，这样到底是方便mindspore自己的开发者，还是方便使用者？

### ISSUE THREAD

**Issue by markovkey** [mindspore-ai/mindspore#267]
![image](https://github.com/mindspore-ai/mindspore/assets/145629295/c69bbd13-72b1-4c90-9f82-e5d1f00bb402)

**Comment by 949144093** [comment]
早期的mindspore算子由于设计问题，很多输入都统一设计成了tensor输入，目前在2.3版本中已经接入了新的range算子，输入均为number，2.2版本可以在mindspore/python/mindspore/ops/auto_generate/gen_ops_def.py中找到range接口定义，也是为输入为number的，或者你可以直接使用ops.arange接口，该接口支持3个输入为任意混合类型，并会自动进行类型推导返回。

**Comment by Ash-Lee233** [comment]
您好，由于问题单没有回复暂时关闭，如您仍有疑问，可以反馈下具体信息，并将ISSUE状态修改为OPEN，我们这边会进一步跟踪，谢谢
