### ISSUE TITLE
[Bug] When there is a negative number in index, 'mindspore.ops.index_select' should throw an error message

### ISSUE THREAD

**Issue by Redmept1on** [mindspore-ai/mindspore#270]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
 `device gpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: v2.2.13
- **Python version (e.g., Python 3.7.5)**: 3.8.18
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04

## Describe the current behavior
[[7. 8. 9.]]

## Describe the expected behavior
IndexError: index out of range in self

## Steps to reproduce the issue
```python
import mindspore as mind
import numpy as np

input_tensor = mind.tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32))

index_tensor = mind.tensor([-1])

output_tensor = mind.ops.index_select(input_tensor, axis=-2, index=index_tensor)

print(output_tensor)
```
![image](https://github.com/mindspore-ai/mindspore/assets/84373897/ce690d59-8bc2-4b78-ac0e-b325a2aca038)

#pytorch v2.0.0+cu117
```python
import torch
import numpy as np

input_tensor = torch.tensor(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

index_tensor = torch.tensor([-1])

output_tensor = torch.index_select(input_tensor, axis=-2, index=index_tensor)

print(output_tensor)
```
![image](https://github.com/mindspore-ai/mindspore/assets/84373897/43bd8ba4-e77a-41d0-9fc3-14cae8022c97)

## Special notes for this issue
The index parameter lacks a range check

**Comment by Ash-Lee233** [comment]
did you test the case on cpu?
we test the case on gpu, it reports the same info as torch
but the cpu gave [[7,8,9]], we will fix it in the next version

**Comment by Redmept1on** [comment]
Thanks for your quick response, sorry for wrong information, after verification I found that my code was running on the CPU.
