### ISSUE TITLE
[Bug] mindspore.ops.argsort/sort perform differently between cpu and gpu.

### ISSUE THREAD

**Issue by Redmept1on** [mindspore-ai/mindspore#277]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> `/device gpu`</br>
> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 2.2.13
- **Python version (e.g., Python 3.7.5)**: 3.8.10
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 22.04
- **GCC/Compiler version (if compiled from source)**: 7.5.0

## Describe the current behavior
mindspore.ops.argsort perform differently between cpu and gpu.

## Describe the expected behavior
the results should be same

## Steps to reproduce the issue
argsort

```python
from mindspore import set_context
import mindspore.ops as ops
import mindspore as mind
import numpy as np

set_context(device_target="CPU")
x1 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y1 = ops.argsort(x1,axis=1)
print(y1)

set_context(device_target="GPU")
x2 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y2 = ops.argsort(x2,axis=1)
print(y2)
```
![image](https://github.com/mindspore-ai/mindspore/assets/84373897/db6466b8-a3cf-49f8-a994-8fcce270f8c3)

sort
```python
from mindspore import set_context
import mindspore.ops as ops
import mindspore as mind
import numpy as np

set_context(device_target="CPU")
x1 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y1 = ops.sort(x1,axis=1)
print(y1)

set_context(device_target="GPU")
x2 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y2 = ops.sort(x2,axis=1)
print(y2)
```
![image](https://github.com/mindspore-ai/mindspore/assets/84373897/aca1f3f5-a56f-4940-866a-06773a2b9857)

**Comment by Redmept1on** [comment]
same issue exists in mindspore.ops.topk
```python
from mindspore import set_context
import mindspore.ops as ops
import mindspore as mind
import numpy as np

set_context(device_target="CPU")
x1 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y1 = ops.topk(x1,2,dim=1)
print(y1)

set_context(device_target="GPU")
x2 = mind.tensor(np.array([[float('inf'), 0, -1, float('nan'), 5]], dtype=np.float32))
y2 = ops.topk(x2,2,dim=1)
print(y2)
```
![image](https://github.com/mindspore-ai/mindspore/assets/84373897/8af7ab3c-14e2-4d66-90be-324374d4061e)

**Comment by Ash-Lee233** [comment]
Hello, I see that you have tested many CPU and GPU API functions. May I ask if you need to use these interfaces for your project?

**Comment by Redmept1on** [comment]
Hello, my current research direction is the fuzzing of DL libraries, so comparing the results of CPU and GPU(or the results of Mindspore and PyTorch/TensorFlow)is a common differential testing method.

**Comment by Ash-Lee233** [comment]
If you can log in to this website: https://gitee.com/mindspore/mindspore/issues, you can submit bug reports, requirements, and other issues to MindSpore. We will designate an enterprise account responsible person and include it in version tracking. GitHub is a mirror repository and currently does not have the function of assigning responsible persons.

**Comment by Redmept1on** [comment]
Thank you for your reply. Do I need to close my issues on github?

**Comment by Ash-Lee233** [comment]
yeah, if you submit on gitee, you can close on github
