### ISSUE TITLE
data sink mode does not work

### ISSUE THREAD

**Issue by Enlion91** [mindspore-ai/mindspore#279]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
ascend 910A， atlas800-9000 server

### Software Environment:
- **MindSpore version (source or binary)**:   2.1.0,  mindyolo 
- **Python version (e.g., Python 3.7.5)**:  Python 3.8.10
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:  Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-125-generic aarch64)
- **GCC/Compiler version (if compiled from source)**:  gcc (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0

## Describe the current behavior
mindyolo, use data sink mode,  train won't start

## Describe the expected behavior
speed up  train

## Steps to reproduce the issue
1.  train with --ms_datasink=True args

## Related log / screenshot
![image](https://github.com/mindspore-ai/mindspore/assets/60950051/5fff41c3-346d-4584-bca2-f28fa2d36197)
it stays here and does not go on

**Comment by Enlion91** [comment]
after  control + c and retart train without data_sink,  it won't start normally, with lots of python process running

![image](https://github.com/mindspore-ai/mindspore/assets/60950051/ec159c59-2907-402d-8c4f-b8ffa7822391)

![image](https://github.com/mindspore-ai/mindspore/assets/60950051/4494980a-9753-4b76-9e38-5da393b80b27)

**Comment by Ash-Lee233** [comment]
we recommend to use default config and dataset to gets the acc and performance in readme
if you remove datasink mode, you may need to change the config to get the network start training
lots of python processing is multiprocessing of data, use parallel function, it is an normal phenomenon

**Comment by Enlion91** [comment]
在华为工程师的帮助下，问题已定位： 子进程不响应退出信号15，流程卡死。临时变更为强制退出规避。
已知问题，在mindspore 2.3 合入了解决措施，但是该措施在我的环境上无效，仍需要kill强制退出。
https://gitee.com/mindspore/mindspore/pulls/66995/files
