### ISSUE TITLE
summaryRecord data not found mindspore 0.3alpha

### ISSUE THREAD

**Issue by MicaTeo** [mindspore-ai/mindspore#35]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**: 0.3 A source
- **Python version (e.g., Python 3.7.5)**: Python 3.7.7
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Linux 18.07
- **GCC/Compiler version (if compiled from source)**: 7.5
- **MindInsight version (source or binary) **: 0.2 A

## Describe the current behaviour
Trying to reproduce the tutorial for mind insight. Using summary record with scalarsummary etc
But having some error on summary_record, not data not found error.
## Steps to reproduce the issue
1. https://www.mindspore.cn/tutorial/zh-CN/master/advanced_use/visualization_tutorials.html
2. 
3.

## Related log / screenshot
![288BB669-4120-40F8-87DE-24AF946CEC60](https://user-images.githubusercontent.com/36864965/83006153-b466b080-a009-11ea-9b1f-0ab83e9f3ccc.jpg)
![7AD03638-17A5-4211-B555-C0A02F80D79F](https://user-images.githubusercontent.com/36864965/83006176-bcbeeb80-a009-11ea-9869-9662b63a25f8.jpg)
![B64A95AE-EFA7-49AC-99EA-5694A6F6AD3D](https://user-images.githubusercontent.com/36864965/83006199-c34d6300-a009-11ea-850d-deff4f982410.jpg)

## Special notes for this issue
The following is my Jupyter Notebook used for trying MindInsight. https://github.com/MicaTeo/mindSpore/blob/master/MindInsight.ipynb

**Comment by wenkai128** [comment]
Hi, I'm WEN Kai from the MindSpore team. Thanks for trying summary operators. Because ScalarSummary and other summary operators are not supported on CPU, there is no summary data recorded. You can try it on GPU or Ascend 910 :)

To get up-to-date operator list information, please visit https://www.mindspore.cn/docs/en/master/operator_list.html
