### ISSUE TITLE
implementation about gpu pool kernel

### ISSUE THREAD

**Issue by zjd1988** [mindspore-ai/mindspore#36]
I am learning \mindspore\ccsrc\kernel\gpu\nn\pooling_gpu_kernel.h code, and find that when pad_mode_ is kSamePadModeUpperCase, needing to perform the pad operation before cudnnPoolingForward.  why not calling cudnnPoolingForward directly by setting pooling_descriptor_ wiht pad para?
![企业微信截图_15905893158763](https://user-images.githubusercontent.com/7134030/83032526-8a90a680-a068-11ea-91aa-a14adf51b9da.png)

Is it any reason about this.

**Comment by VectorSL** [comment]
Yes, cudnn supports the setting of pad parameters(we used it indefault), but only provides the parameters of two dimensions, and the pad value is the same in top and bottom. When the top and bottom pads calculated by the same pad mode are different, cudnn's own interface does not support this situation (such as top pad = 1, bottom pad = 2), so here the `CalPad` func is used to deal with this situation, which is controlled by `use_pad`.

**Comment by zjd1988** [comment]
@VectorSL  OK, I get it. Thanks for your reply! :+1:
