### ISSUE TITLE
gpu softmax kernel problem

### ISSUE THREAD

**Issue by zjd1988** [mindspore-ai/mindspore#37]
I am learning softmax gpu kernel， and I have a question about this code
![企业微信截图_15906459598073](https://user-images.githubusercontent.com/7134030/83105126-a3db3680-a0ec-11ea-9f8d-2d69a8d09468.png)

Once mode_ variable was set CUDNN_SOFTMAX_MODE_INSTANCE, and never be changed 
when axis_ variable is 1 or 0, mode_ should equal to CUDNN_SOFTMAX_MODE_CHANNEL.
![企业微信截图_15906463744716](https://user-images.githubusercontent.com/7134030/83105507-61fec000-a0ed-11ea-84b5-82cd5eba2442.png)

**Comment by limingqi107** [comment]
Currently only the INSTANCE mode is supported. When the input dimension is 2-D, set H and W to 1. When the input dimension is N-D, only the axis is supported as the last dimension, and converted to 2-D processing.
In addition, when H and W are 1, the result of using INSTANCE mode and CHANNEL mode is the same.
In the future, any axis in the N-D input and the CHANNEL mode will be supported.

**Comment by zjd1988** [comment]
@limingqi107  OK, I get it. Thanks for your reply.
