### ISSUE TITLE
if my dataset is csv file, how could I do to load my dataset as input to the mindspore

### ISSUE THREAD

**Issue by judong-520** [mindspore-ai/mindspore#42]
if my dataset is csv file, how could I load my dataset as input to hte mindspore

**Comment by judong-520** [comment]
it seems that pass an obj as input to the mindspore model,how could i define my data obj?

**Comment by yingjiangyong** [comment]
Yes, MindSpore model needs an object of MindSpore Dataset. For csv files, now (0.3.0 release version), there are 2 ways:
	1. Define a GeneratorDataset (API doc:
	https://www.mindspore.cn/api/zh-CN/master/api/python/mindspore/mindspore.dataset.html#mindspore.dataset.GeneratorDataset).  You need to define a function to parse your csv files as input of 'source' parameter of GeneratorDataset. In your parsing function, you could use whatever third-party packages to process your csv files, e.g., pandas, numpy. 
	2. Convert csv files into mindrecord format, and then define a MindDataset.
	This is a high-performance way to deal with various datasets. In general scenario, MindDataset costs less time than GeneratorDataset. Please check the following reference: 
	https://www.mindspore.cn/tutorial/en/master/use/data_preparation/converting_datasets.html
	https://www.mindspore.cn/api/en/0.3.0-alpha/api/python/mindspore/mindspore.dataset.html#mindspore.dataset.MindDataset

Actually, both GeneratorDataset and mindrecord are very flexible ways to load dataset. They can almost deal with any dataset.
