### ISSUE TITLE
Load onnx model by mindspore

### ISSUE THREAD

**Issue by stereomatchingkiss** [mindspore-ai/mindspore#49]
Is it possible to load the onnx model by mindspore? pytorch has many interesting projects and models(ex : [yolov4](https://github.com/Tianxiaomo/pytorch-YOLOv4) and [yolov5](https://github.com/ultralytics/yolov5)), would be great if we could reuse them rather than rewrite the codes and train the model from scratch(only mindspore able to leverage the power of Ascend310). 

Similar issue is #23

**Comment by jluleilei** [comment]
The onnx model is not supported now, and will be considered in the future.

**Comment by stereomatchingkiss** [comment]
> Load the onnx model is not supported now, and will be considered in the future.

Thanks, hope it could be considered as a key features, mindspore enter the market pretty late, we need more pretrained model.
