### ISSUE TITLE
BatchNorm2D throw exception

### ISSUE THREAD

**Issue by stereomatchingkiss** [mindspore-ai/mindspore#50]
## Environment
os : win10 64bits
mindspore version : mindspore-0.5.0-cp37-cp37m-win_amd64.whl
python : 3.7.5(anaconda)
CPU : True

## Describe the current behavior
The lenet do not work after apply BatchNorm2d

## Describe the expected behavior
lenet work after apply BatchNorm2d

## Steps to reproduce the issue
1. Copy the codes at [pastebin](https://pastebin.com/VJADCEx0) to main.py
2.  Create folder data
3.  Create two folders(whatever names you like) and put some images(no less than 32) inside each of them
4.  python main.py

## Related log / screenshot

```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    model.train(args.epoch, dataset_train, callbacks=[ckpoint_cb, LossMonitor()], dataset_sink_mode=False)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\train\model.py", line 535, in train
    dataset_sink_mode=dataset_sink_mode)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\train\model.py", line 357, in _train
    self._train_process(epoch, train_dataset, list_callback, cb_params)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\train\model.py", line 468, in _train_process
    outputs = self._train_network(*next_element)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\nn\cell.py", line 212, in __call__
    out = self.compile_and_run(*inputs)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\nn\cell.py", line 411, in compile_and_run
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "C:\Users\yyyy\Anaconda3\envs\mindspore\lib\site-packages\mindspore\common\api.py", line 417, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore\ccsrc\session\anf_runtime_algorithm.cc:555 GetOutputDeviceDataType] Node [kernel_graph_0:equivdout{[0]: ValueNode<Primitive> FusedBatchNorm, [1]: equivdout, [2]: conv1BatchNorm.gamma, [3]: conv1BatchNorm.beta, [4]: conv1BatchNorm.moving_mean, [5]: conv1BatchNorm.moving_variance}] has a invalid dtype
```

## Special notes for this issue

Works well without the batchnorm layer. Not sure if this is the issue on windows only, will test it on ubuntu16.04.

**Comment by DouSong** [comment]
Well, BatchNorm2d is not supported by CPU now, but it's supported by GPU&Ascend. You can visit this website to get more information : https://www.mindspore.cn/docs/zh-CN/master/operator_list.html

**Comment by stereomatchingkiss** [comment]
> Well, BatchNorm2d is not supported by CPU now, but it's supported by GPU&Ascend. You can visit this website to get more information : https://www.mindspore.cn/docs/zh-CN/master/operator_list.html

Thanks, switch to gpu works now.
Mindspore join the market quite late, guess Huawei need to hire more engineers to make it evolve faster in order to compete with other competitiors, since most of the users would prefer pytorch or tensorflow(yawk!!!) under current states. 
Good luck and hope this going well.
