### ISSUE TITLE
Auto-parallel tutorial/example?

### ISSUE THREAD

**Issue by eric-haibin-lin** [mindspore-ai/mindspore#53]
Hi Mindspore community,

Where can i find example code or tutorial for auto-parallel and distributed autodiff? Thanks!

**Comment by DouSong** [comment]
Well, you can refer to this tutorial [autu-parallel]( https://www.mindspore.cn/tutorial/en/master/advanced_use/distributed_training.html)
![image](https://user-images.githubusercontent.com/17930233/87107254-dbafcf00-c291-11ea-8ff1-501fe1656578.png)
