### ISSUE TITLE
Compile error not friendly

### ISSUE THREAD

**Issue by LyricZhao** [mindspore-ai/mindspore#59]
### Hardware Environment: 
> `/device gpu`</br>

### Software Environment:
- **MindSpore 0.5.0 (from binary)**
- **Python 3.7.5**
- **Linux Ubuntu 18.04.4 LTS**

## Bug report
I simply define several `ms_function` and want to get the grad of the input, just like below:

```python
import numpy as np

from mindspore import ms_function
from mindspore import context
from mindspore import Tensor
import mindspore.ops.composite as C
import mindspore.ops.functional as F
import mindspore.ops.operations as P
import mindspore

# Runtime configs
context.set_context(mode=context.GRAPH_MODE, device_target='GPU')

# Functions
reduce_sum = P.ReduceSum()


@ms_function
def f_1_can_not_run(x):
    y = reduce_sum(x * x, -1)
    y = F.sqrt(y)
    return y


@ms_function
def f_2_can_run(x):
    y = reduce_sum(x * x, -1)
    return y


@ms_function
def f_3_can_run(x):
    y = F.sqrt(x)
    return y


x = Tensor(np.random.normal(size=(32, 2)), dtype=mindspore.float32)
print(C.grad(f_1_can_not_run)(x))  # compile error

x = Tensor(np.random.normal(size=(32, 2)), dtype=mindspore.float32)
print(C.grad(f_2_can_run)(x))

x = Tensor(np.random.normal(size=(32,)), dtype=mindspore.float32)
print(C.grad(f_3_can_run)(x))
```

But the function `f_1_can_not_run` got compiler error below:

```
RuntimeError: mindspore/ccsrc/kernel/akg/gpu/akg_gpu_kernel_build.cc:34 AkgGpuKernelBuild] : The pointer[kernel_pack] is null.
```

While deleting the `print(C.grad(f_1_can_not_run)(x))` line, `f_2_can_run` and `f_3_can_run` are behaving as expected.

Is something wrong with my usages? Or is it a bug?

**Comment by wuyanernuo7** [comment]
The reason of this error  is nvcc compiler can not be found, please add nvcc position to the Path environment variable , you could run the command: export PATH=${CUDA_PATH}/bin:$PATH ,
CUDA_PATH is the installation path of the cuda library (eg. /usr/local/cuda), and try to run nvcc to test if the path is set correctly.

**Comment by LyricZhao** [comment]
It works! Thanks for your comments.

Running it in PyCharm remote leads to the PATH problem.

**Comment by LyricZhao** [comment]
What's more, I think maybe a friendly error message could be an enhancement.

**Comment by wuyanernuo7** [comment]
Thanks for your suggestions. We will refine the error message in later versions.

**Comment by leonwanghui** [comment]
Will close this issue for having been resolved, @LyricZhao plz be free to reopen it if required : )
