### ISSUE TITLE
端侧推理的lite目前稳定么？

### ISSUE THREAD

**Issue by sdualasijia** [mindspore-ai/mindspore#66]
我之前将只包含conv2d 3x3 stride = 1 ，dataformat = nhwc 的 tf pb 模型首先转换为 tflite，然后再转换为 .ms 文件，但是执行结果与原始的 pb 不一致，Convolution3x3CPUKernel 的实现是不是存在问题？

**Comment by cogbee** [comment]
同样的，我也将一个 conv2d 3x3 stride = 1 ，dataformat = nhwc 的 tf pb 模型转换成 ms 模型，运行结果跟原始 tf 不一致。

master 分支 Convolution3x3CPUKernel 的实现是不是错误的？

**Comment by alexchai** [comment]
感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理

**Comment by cogbee** [comment]
> 感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理

点赞，期待更新

**Comment by sdualasijia** [comment]
> 感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理

手动点赞~~

**Comment by cogbee** [comment]
> 感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理

我在问下，https://github.com/mindspore-ai/mindspore/blob/master/mindspore/lite/src/runtime/kernel/arm/nnacl/fp32/conv_depthwise.c#L220  为啥 arm64 有汇编实现，arm32 就没用用汇编？性能差太多了。我看 arm32 也有汇编的实现，为何不直接调用？

**Comment by sdualasijia** [comment]
> 感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理

Convolution3x3CPUKernel 问题解决了么？

**Comment by yangruoqi** [comment]
> > 感谢关注，我们推理框架目前处于开发阶段，Convolution3x3的问题我们已经发现，当前正在处理
> 
> Convolution3x3CPUKernel 问题解决了么？

Convolution3x3CPUKernel已经解决
