### ISSUE TITLE
Can not parse constant in auto parallel mode

### ISSUE THREAD

**Issue by LyricZhao** [mindspore-ai/mindspore#67]
### Hardware Environment:
GPU: 8 x NVIDIA P100

### Software Environment:
- **MindSpore version**: 0.6.0
- **Python version**: Python 3.7.5
- **OS platform and distribution**: Linux Ubuntu 18.04

## Describe the current behavior
Hi, I'm working on a Molecular Dynamics simulation using MindSpore. And currently I want to boost my code using `auto_parallel` mode. However, the analyzer failed to parse a multiplication with a constant (https://github.com/LyricZhao/MindSpore-MD/blob/auto-parallel-bug/mindspore_multi_gpu.py#L39) while it's working again without `auto_parallel` mode or deleting the constant.

## Steps to reproduce the issue
- Download the code file https://github.com/LyricZhao/MindSpore-MD/blob/auto-parallel-bug/mindspore_multi_gpu.py
- Change line 40 following the comments in line 39
- Run the single file with MPI like `mpirun -n 8 python mindspore_multi_gpu.py`

## Related log
```
Traceback (most recent call last):
  File "mindspore_multi_gpu.py", line 86, in <module>
    times = run(100)
  File "mindspore_multi_gpu.py", line 74, in run
    R = model.predict(R, Tensor(0))
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/model.py", line 713, in predict
    result = self._predict_network(*predict_data)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 227, in __call__
    out = self.compile_and_run(*inputs)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 449, in compile_and_run
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 425, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/frontend/parallel/step_parallel.cc:1075 GetNodeShape] GetNodeShape: [CNode]73 shape_ptr is nullptr, full name is Default/Mul-op0
[ERROR] PARALLEL(50690,python):2020-08-16-06:58:35.264.640 [mindspore/ccsrc/frontend/parallel/step_parallel.cc:1075] GetNodeShape] GetNodeShape: [CNode]73 shape_ptr is nullptr, full name is Default/Mul-op0
Traceback (most recent call last):
  File "mindspore_multi_gpu.py", line 86, in <module>
    times = run(100)
  File "mindspore_multi_gpu.py", line 74, in run
    R = model.predict(R, Tensor(0))
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/train/model.py", line 713, in predict
    result = self._predict_network(*predict_data)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 227, in __call__
    out = self.compile_and_run(*inputs)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/nn/cell.py", line 449, in compile_and_run
    _executor.compile(self, *inputs, phase=self.phase, auto_parallel_mode=self._auto_parallel_mode)
  File "/home/zhaocg/.local/miniconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/common/api.py", line 425, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/frontend/parallel/step_parallel.cc:1075 GetNodeShape] GetNodeShape: [CNode]73 shape_ptr is nullptr, full name is Default/Mul-op0
```

**Comment by Simson1996** [comment]
Hi Lyric, thanks for your question!

This is actually an issue in the optimization phase. These kind of continuous constants would be optimized as a tensor. In this case,  `0.5 * 0.5`  was optimized as a tensor with value 0.25. However, the shape of it was not set timely in the phase.

In non-automatic parallel mode, the shape is re-derived in a pass in the last of the optimization phase, and there is no other pass need to use the shape. Therefore, no error occurs in non-automatic parallel mode. On the contrary, the shape is required in the automatic parallel mode before it is re-derived, in which case a null pointer is obtained.

We will fix the issue ASAP, thanks again!

**Comment by LyricZhao** [comment]
> Hi Lyric, thanks for your question!
> 
> This is actually an issue in the optimization phase. These kind of continuous constants would be optimized as a tensor. In this case, `0.5 * 0.5` was optimized as a tensor with value 0.25. However, the shape of it was not set timely in the phase.
> 
> In non-automatic parallel mode, the shape is re-derived in a pass in the last of the optimization phase, and there is no other pass needs to use the shape. Therefore, no error occurs in non-automatic parallel mode. On the contrary, the shape is required in the automatic parallel mode before it is re-derived, in which case a null pointer is obtained.
> 
> It is recommended that you use `0.25` instead of `0.5 * 0.5` for the moment, it will work well!
> 
> We will fix the issue ASAP, thanks again!

Thanks for your reply!

**Comment by Simson1996** [comment]
> > Hi Lyric, thanks for your question!
> > This is actually an issue in the optimization phase. These kind of continuous constants would be optimized as a tensor. In this case, `0.5 * 0.5` was optimized as a tensor with value 0.25. However, the shape of it was not set timely in the phase.
> > In non-automatic parallel mode, the shape is re-derived in a pass in the last of the optimization phase, and there is no other pass needs to use the shape. Therefore, no error occurs in non-automatic parallel mode. On the contrary, the shape is required in the automatic parallel mode before it is re-derived, in which case a null pointer is obtained.
> > It is recommended that you use `0.25` instead of `0.5 * 0.5` for the moment, it will work well!
> > We will fix the issue ASAP, thanks again!
> 
> Thanks for your reply!

This issue has been fixed in PR: https://gitee.com/mindspore/mindspore/pulls/4698. Now you could use any operation between constants as you want!
