### ISSUE TITLE
Can not parse Tensor shape in graph mode

### ISSUE THREAD

**Issue by LyricZhao** [mindspore-ai/mindspore#70]
Hi, it's really convenient to get the shape of the Tensor and use the shape for randomize another Tensor in PyNative mode. However, it seems not working during the compilation of graph mode.

For example:
```python
import mindspore.nn as nn
import mindspore.ops.operations as P
from mindspore import context

class Cell(nn.Cell):
    def __init__(self, n):
        super(Cell, self).__init__()
        self.n = n
        self.random = P.StandardNormal()

    def construct(self, x):
        # Can not get x.shape in graph mode
        y = self.random(x.shape)
        return x + y

if __name__ == '__main__':
    # Working only in PyNative mode
    context.set_context(mode=context.GRAPH_MODE)
    cell = Cell(4096)
    x = cell.random((4096, ))
    print(cell(x))
```

And my suggestion to the problem is to just maybe define `shape` as a reserved word during the Python parsing and complication.

Or another solution (not elegant) is to make new operators like `torch.randn_like(torch.Tensor)` (https://pytorch.org/docs/stable/generated/torch.randn_like.html), which uses the whole tensor as an input :)

**Comment by buxue0727** [comment]
Yeah，as you can see, In version 0.6, the shape and dtype attributes of the tensor can be called only in the Pynative mode, and is not supported in graph mode. 
It will be supported in version 0.7.
In the PR：https://gitee.com/mindspore/mindspore/pulls/3820

**Comment by LyricZhao** [comment]
> Yeah，as you can see, In version 0.6, the shape and dtype attributes of the tensor can be called only in the Pynative mode, and is not supported in graph mode.
> It will be supported in version 0.7.
> In the PR：https://gitee.com/mindspore/mindspore/pulls/3820

Thanks for your reply! You can close this issue freely when merged.

**Comment by buxue0727** [comment]
Sorry，I don't have access to close the issue. The PR is already merged. In version 0.7, it will supported.
