### ISSUE TITLE
How to extract the features from the model?

### ISSUE THREAD

**Issue by nan-wang** [mindspore-ai/mindspore#76]
From the [`LeNet` example from the tutorial](https://www.mindspore.cn/tutorial/zh-CN/r0.6/quick_start/quick_start.html), I want to extract the feature vectors from the 2nd last layer of a trained network. 
Would you please offer some code snippets for this task?

As for getting the outputs of the last layer is quite clear.
```
    network = LeNet5()
    param_dict = load_checkpoint("checkpoint_lenet-1_1875.ckpt")
    #load parameter to the network
    load_param_into_net(network, param_dict)
    output = network(x)
```

mindspore version: 0.6.0-beta

**Comment by DouSong** [comment]
```Print``` operation may help you,
![image](https://user-images.githubusercontent.com/17930233/90507948-56211800-e189-11ea-814a-636a3736e861.png)
You can visit this [page](https://www.mindspore.cn/api/zh-CN/master/api/python/mindspore/mindspore.ops.operations.html#mindspore.ops.operations.Print) to get more details.

**Comment by nan-wang** [comment]
hi, @DouSong Thanks for your quick response. I'm afraid `Print` is not what I'm looking for.

```
class LeNet5(nn.Cell):
    ...

    # use the preceding operators to construct networks
    def construct(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x

if __name__ == '__main__':
    ...
    network = LeNet5()
    model = Model(network, ...)
    ...

    # train the model
    ...
    model.train(...)
    ...

    # load the model
    param_dict = load_checkpoint("checkpoint_lenet-1_1875.ckpt")
    # load parameter to the network
    load_param_into_net(network, param_dict)
    
    # extract features  
    ...  
    output = network(my_input)
    
```

As shown above, after loading the trained model, `network(input)` will output the results from the last layer, i.e. `fc3()`. What I need is the outputs from `fc2()` while keeping the training part untouched.

**Comment by DouSong** [comment]
Hi @nan-wang , you can have a try like this~
![image](https://user-images.githubusercontent.com/17930233/90634956-20e4fa80-e25b-11ea-9387-78172ea3fd9f.png)

**Comment by nan-wang** [comment]
hi, @DouSong The point is that I need to assign the results to a variable rather than outputting to stdout. Here the tweak I've made so far, and it is like a hacking. It would be great if you can shed more lights on how to do this properly.

```
class LeNet5(nn.Cell):
    ...

class LeNet5Feature(LeNet5):
    ...

    # use the preceding operators to construct networks
    def construct(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        # remove the last operation
        # x = self.fc3(x) 
        return x

if __name__ == '__main__':
    ...
    network = LeNet5()
    model = Model(network, ...)
    ...

    # train the model
    ...
    model.train(...)
    ...

    # load the model
    param_dict = load_checkpoint("checkpoint_lenet-1_1875.ckpt")

    network_for_feat_extraction = LeNet5Feature()
    # load parameter to the network
    load_param_into_net(network_for_feat_extraction, param_dict)
    
    # extract features  
    ...  
    output = network_for_feat_extraction(my_input) 
```

**Comment by Simson1996** [comment]
Hi @nan-wang, I guess the doc will help:  
https://www.mindspore.cn/tutorial/zh-CN/master/advanced_use/customized_debugging_information.html#dump

In graph mode, you can dump the input and output of every operations you want. Is it the point?

**Comment by nan-wang** [comment]
@Simson1996 Thanks for your comments. Good to know about `Dump`! I think `Dump` is more about dumping the data to files. However, I want to assign the intermedia output to a variable. In other words, I am wondering how to run a subgraph in mindspore.

**Comment by gziyan-ms** [comment]
hi @nan-wang, actually we support assigning an intermedia output to a variable. And before that you should know the shape of the intermedia result you want to use. Here is an example:
```
class LeNet5Feature(LeNet5):
    def __init__(self):
        self.my_var = Parameter(Tensor(np.zeros([...])), name="my_var")
     ...
     
    # use the preceding operators to construct networks
    def construct(self, x):
        x = self.conv1(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.conv2(x)
        x = self.relu(x)
        x = self.max_pool2d(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        inter_out = self.relu(x)
        x = self.fc3(inter_out) 
        return F.depend(x, F.assign(self.var, inter_out))
``` 
Hope that helps!  : )

**Comment by nan-wang** [comment]
@gziyan-ms Great! That's really helpful!
