### ISSUE TITLE
Can't Find the Implementation of ge::model_runner::ModelRunner

### ISSUE THREAD

**Issue by DW9363** [mindspore-ai/mindspore#8]
Seems like i can't find the related codes of ge::model_runner::ModelRunner,  or namespace model_runner,  anyone knows ?

**Comment by leonwanghui** [comment]
Hi @DW9363 , the `ModelRunner` class is hosted in these two files below:

- https://github.com/mindspore-ai/graphengine/blob/master/src/ge/ge_runtime/model_runner.cc
- https://github.com/mindspore-ai/graphengine/blob/master/inc/framework/ge_runtime/model_runner.h

Please be free to ask if you have any question : )

**Comment by DW9363** [comment]
> Hi @DW9363 , the `ModelRunner` class is hosted in these two files below:
> 
> * https://github.com/mindspore-ai/graphengine/blob/master/src/ge/ge_runtime/model_runner.cc
> * https://github.com/mindspore-ai/graphengine/blob/master/inc/framework/ge_runtime/model_runner.h
> 
> Please be free to ask if you have any question : )

Thanks,  just got another question, is the lib "fwkacllib" in graphengine  open source ?  if  it is, where can i find the related codes ?

**Comment by leonwanghui** [comment]
> Thanks, just got another question, is the lib "fwkacllib" in graphengine open source ? if it is, where can i find the related codes ?

@jzh-liu Could you answer this question? Thanks!

**Comment by jzh-liu** [comment]
Hi @DW9363 , fwkacllib is a 3rdpart component which belongs to Huawei AI process Ascend CANN（Compute Architecture for Neural Networks）. It is not open source yet. The header files are here:
https://github.com/mindspore-ai/graphengine/tree/master/third_party/fwkacllib

**Comment by DW9363** [comment]
> Hi @DW9363 , fwkacllib is a 3rdpart component which belongs to Huawei AI process Ascend CANN（Compute Architecture for Neural Networks）. It is not open source yet. The header files are here:
> https://github.com/mindspore-ai/graphengine/tree/master/third_party/fwkacllib

Thanks,  I saw the heads.
