### ISSUE TITLE
does BatchNorm1d not support Dense?

### ISSUE THREAD

**Issue by zhen8838** [mindspore-ai/mindspore#86]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
GPU and CPU

### Software Environment:

install from official's docker image

- **MindSpore version (source or binary)**: 0.7.0 beta
- **Python version (e.g., Python 3.7.5)**: Python 3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**:  7.4.0

## Describe the current behavior

in GPU:
```python
ms.context.set_context(mode=0, device_target='GPU')
noise = ms.Tensor(np.random.rand(8, 100), dtype=ms.float32)
noise = ml.Dense(100, 7 * 7 * 256, has_bias=False)(noise)
noise = ml.BatchNorm1d(7 * 7 * 256)(noise)
```
output:
```
RuntimeError: mindspore/ccsrc/backend/kernel_compiler/gpu/nn/fused_batch_norm_gpu_kernel.h:93 Init] tensor shape is 2, FusedBatchNormGpuKernel should be >= 4
```

in CPU:

```python
ms.context.set_context(mode=0, device_target='CPU')
noise = ms.Tensor(np.random.rand(8, 100), dtype=ms.float32)
noise = ml.Dense(100, 7 * 7 * 256, has_bias=False)(noise)
noise = ml.BatchNorm1d(7 * 7 * 256)(noise)
```
output:
```
RuntimeError: mindspore/ccsrc/backend/kernel_compiler/cpu/mkldnn/fused_batch_norm_cpu_kernel.cc:43 InitKernel] fused batchnorm only support nchw input!
```

## Steps to reproduce the issue

```python
import mindspore.nn.layer as ml
import mindspore as ms
import numpy as np
ms.context.set_context(mode=1, device_target='GPU')
noise = ms.Tensor(np.random.rand(8, 100), dtype=ms.float32)
noise = ml.Dense(100, 7 * 7 * 256, has_bias=False)(noise)
noise = ml.BatchNorm1d(7 * 7 * 256)(noise)
```

## Special notes for this issue

refer from document also report error:
https://www.mindspore.cn/api/zh-CN/r0.7/api/python/mindspore/mindspore.nn.html?highlight=batchnorm1d#mindspore.nn.BatchNorm1d

```python
from mindspore import Tensor
from mindspore import nn
import mindspore 
net = nn.BatchNorm1d(num_features=16)
input = Tensor(np.random.randint(0, 255, [3, 16]), mindspore.float32)
net(input)
```
```
RuntimeError: mindspore/ccsrc/backend/kernel_compiler/gpu/nn/fused_batch_norm_gpu_kernel.h:93 Init] tensor shape is 2, FusedBatchNormGpuKernel should be >= 4
```

**Comment by VectorSL** [comment]
Thank you for your attention. However, BatchNorm1d is not supported in GPU/CPU now. You can obtain the supported op lists in [mindspore docs]( https://www.mindspore.cn/docs/en/master/operator_list.html).  And it may be done in the future. Also, it is highly recommended to try to implement it yourself. Thanks.

**Comment by zhen8838** [comment]
thanks for replay.I will try to implement.
