### ISSUE TITLE
MindSpore 1.0.0 conflict with CUDA 10.1 Installation

### ISSUE THREAD

**Issue by sliawatimena** [mindspore-ai/mindspore#89]
Dear all,

### Hardware Environment(`GPU`): 
`/device gpu`</br>

### Software Environment:
**MindSpore version (source or binary)**: pip install
**Python version (e.g., Python 3.7.5)**: 3.7.5
**OS platform and distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
**GCC/Compiler version (if compiled from source)**: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

## Describe the current behavior
OSError: MindSpore version 1.0.0 and cuda version 10.0 does not match,

## Describe the expected behavior
Mindspore should be imported normally.

## Steps to reproduce the issue
1. 
pip install https://ms-release.obs.cn-north-4.myhuaweicloud.com/1.0.0/MindSpore/gpu/ubuntu_x86/cuda-10.1/mindspore_gpu-1.0.0-cp37-cp37m-linux_x86_64.whl
2. python
3. >> import mindspore
```
Python 3.7.5 (default, Sep 16 2020, 23:41:33) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mindspore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/suryadi/.local/lib/python3.7/site-packages/mindspore/__init__.py", line 17, in <module>
    from ._version_check import check_version_and_env_config
  File "/home/suryadi/.local/lib/python3.7/site-packages/mindspore/_version_check.py", line 256, in <module>
    check_version_and_env_config()
  File "/home/suryadi/.local/lib/python3.7/site-packages/mindspore/_version_check.py", line 250, in check_version_and_env_config
    env_checker.check_version()
  File "/home/suryadi/.local/lib/python3.7/site-packages/mindspore/_version_check.py", line 95, in check_version
    raise EnvironmentError(f"MindSpore version {__version__} and cuda version {v_str} does not match, "
OSError: MindSpore version 1.0.0 and cuda version 10.0 does not match, reference to the match info on: https://www.mindspore.cn/install
```

## Related log / screenshot
![image](https://user-images.githubusercontent.com/255019/94589904-14b77880-02b0-11eb-93b1-30eb102f90b8.png)

![image](https://user-images.githubusercontent.com/255019/94589872-05d0c600-02b0-11eb-9392-75a1edaa7e04.png)

## Special notes for this issue

How to fix this? Thank you very much in advance.

Warmest regards,
Suryadi

**Comment by wuyanernuo7** [comment]
MindSpore 1.0.0 GPU version supports only CUDA 10.1, please change the soft link file "/usr/local/cuda" links to /usr/local/cuda-10.1, or delete the soft link file "/usr/local/cuda , we will refine CUDA version checker in later MindSpore version.

**Comment by sliawatimena** [comment]
![image](https://user-images.githubusercontent.com/255019/94643089-38aaa680-0310-11eb-97a0-d424d2210725.png)
![image](https://user-images.githubusercontent.com/255019/94643110-42340e80-0310-11eb-9fc2-df8fe1f43e00.png)

After correcting link cuda --> cuda-10.1, then mindspore 1.0.0 can be installed (with error message, but it run).
Thank you very much.

Suryadi
