### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by Yiltan** [mindspore-ai/mindspore#91]
Hi I'm trying to install MindSpore but I am having the following issue.

I am installing it on an x86_64 platform (CentOS 7.3) with GPUs (CUDA 10.2) . I am installing it using the following command:
```export CUDNN_HOME=/opt/cudnn/ ./build.sh -e GPU```

I get the following error and I cannot install it

```
....
pkg name:ms_onnx,ms_onnx
ms_onnx config hash: c8ce681e4f99ac07d2b8d101f7871f56
-- Found Python3: /opt/bin/python3.7 (found suitable version "3.7.7", minimum required is "3.7") found components: Interpreter Development 
PYTHON_INCLUDE_DIRS = /opt/include/python3.7m
PYTHON_LIBRARIES = /opt/python/3.7.7/lib/libpython3.7m.so
CMake Error at mindspore/ccsrc/CMakeLists.txt:40 (message):
  Failed to find cudnn library file, please set environment variable
  CUDNN_HOME to cudnn installation position.
...
```

Do you have any suggestions on how to solve this?

**Comment by wuyanernuo7** [comment]
The error occurs when failed to find cudnn library file,  if cudnn library is installed in user defined position, please set environment variable CUDNN_HOME to cudnn installation position, there should be cudnn library file in {CUDNN_HOME}/lib64, so please check your CUDNN_HOME , i.e. "/opt/cudnn/";
if cudnn library is not installed, please put cudnn library file in cuda library path or user library path(eg. /usr/local/cuda/lib64; /usr/local/lib64; /usr/lib64; /usr/local/lib; /usr/lib).
