### ISSUE TITLE
Miss package libnuma-dev in devel container

### ISSUE THREAD

**Issue by Shenggan** [mindspore-ai/mindspore#92]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 

`/device gpu`

### Software Environment:
- **MindSpore version (source or binary)**: 1.0.1(source)
- **Python version (e.g., Python 3.7.5)**: Python 3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**: GCC 7.5.0

## Describe the current behavior

Use devel container ([Dockerfile](https://github.com/mindspore-ai/mindspore/blob/master/docker/mindspore-gpu/devel/Dockerfile)) to build mindpore from source.

`bash ./build.sh -e gpu`

and get error from:

[mindspore/ccsrc/minddata/dataset/engine/cache/CMakeLists.txt#L27](https://github.com/mindspore-ai/mindspore/blob/master/mindspore/ccsrc/minddata/dataset/engine/cache/CMakeLists.txt#L27)

## Describe the expected behavior

I think the package `libnuma-dev` should be installed in devel environment not only GPU.

**Comment by jonyguo** [comment]
Thank you very much for your advice.

Next, we will install libnuma-dev in our docker with different env(GPU/Ascend/CPU) in advance. Do you think this is correct?

**Comment by Shenggan** [comment]
That great, I think it is correct. And I would like to help if you need.

**Comment by leonwanghui** [comment]
@Shenggan Thanks for reporting the issue, and it has been addressed by https://gitee.com/mindspore/mindspore/pulls/9818.

**Comment by Shenggan** [comment]
Thanks for such a quick reply! Issue close.
