### ISSUE TITLE
"add schema version" breaks schema compatibility

### ISSUE THREAD

**Issue by lutzroeder** [mindspore-ai/mindspore#93]
Changes like adding a new `version` field to an existing table in https://github.com/mindspore-ai/mindspore/commit/b6493c209f5b3ebe64ac5533471fdecd97d44719 are not allowed in FlatBuffers as they will change the file layout and break compatibility.

@zhaodezan @YvetteLaw

**Comment by andeyeluguo** [comment]
Hi, lutzroeder Yes, you are right that they will change the file layout and may break compatibility, but the pr is pulled to solve the compatibility of version. We had better not add field to table, but sometimes we must do that. When the converted model(.ms format) version and the benchmark(the code you run the model) version is not the same, will raise this warning.
![image](https://user-images.githubusercontent.com/12607564/102032572-1e9f4100-3df4-11eb-8b26-d80973fdbf48.png)
what we should do is keeping the version of convert and benchmark the same. If something is wrong, you may recompile the code convert and benchmark.

**Comment by lutzroeder** [comment]
@andeyeluguo this will not work and is the incorrect way to add to a table. You are breaking other tools that try to read these files and users will see crashes or cryptic error messages. Please read "Schema evolution examples" in [md__schemas](https://google.github.io/flatbuffers/md__schemas.html) and follow these rules.
